### PR TITLE
Resprites Service Uniforms & Adds Rolled Sleeve Variants

### PR DESCRIPTION
**Pull request by DangerRevolution**
# Description

This PR resprites the service uniforms with the Aurora variants, as well as doing minor yaml cleanup for the base_clothinguniforms.yml

Aurora has 2-3 variants for service staff; based on which company they're associated with. So far I've just picked the Nanotrasen variant, because SS14 uses Nanotrasen.

My question is:
A) Should I port the extra uniforms and stick them in loadouts, for variety & drip?
  i) Should I keep the company names on these uniforms if I port them, or should I keep it 
     Nanotrasen?

This PR also removes in-hand variants; they're not supported in aurora and it's not critical game info to see someone carrying a shirt & pants.

This PR similarly removes the animal variants; the Vox PR should have displacement maps to support it.

---

# TODO

- [X] Bartender Jumpsuit
- [X] Bartender Vest
- [X] Bartender Hat

- [X] Janitor Jumpsuit
- [X] Chef Jumpsuit
- [X] Chef Freezer Jacket
- [X] Chef Hat

- [X] Botanist Uniform
- [x] Librarian Uniform 
  ^ Librarian Jumpsuit has been added with four extra variants, some corporations who do not employ Librarians still have jumpsuit sprites.

---

<details><summary><h1>Media</h1></summary>
<p>

## Nanotrasen Bartender

image
image
image
image

## Nanotrasen Chef

image
image
image
image

## Nanotrasen Botanist

image
image
image
image

## Nanotrasen Janitor

image
image
image
image

## Nanotrasen Librarian

image
image
image
image

</p>
</details>

---

# Changelog

:cl: DangerRevolution
- add: Resprited basic Service Staff uniforms
- add: Add rolled sleeve variants for Service Staff uniforms.

### CODE REVIEW

**Comment by DangerRevolution** [comment]
Media attached; need thoughts on:
> My question is:
A) Should I port the extra uniforms and stick them in loadouts, for variety & drip?
i) Should I keep the company names on these uniforms if I port them, or should I keep it
Nanotrasen?

**Comment by VMSolidus** [comment]
1. Should I port the extra uniforms and stick them in loadouts, for variety & Drip?
ABSOLUTELY YES. 

2. Should I keep the company names on these uniforms if I port them, or should I keep it Nanotrasen?
You actually should keep the company names on the uniforms. Me and Death are cooking our own take on the Records page with Loadout Integrations, and one of the options is a button for selecting "Employment Status", between either working for Nanotrasen, or as a Contractor from another corporation(Selected from YML Prototypes), and we wanted Loadout integrations with this. For example picking Hephaeustus Heavy Industries as a Contractor status locks a character to Engineering roles, but now their engineering loadouts allow them to pick up Hephaeustus equipment variants.

**Comment by DangerRevolution** [comment]
@VMSolidus Second problem is that the majority of these uniforms do *not* have jumpskirt variants, I'm more than happy to throw the tag on so Harpies can wear them though.

**Comment by VMSolidus** [comment]
> @VMSolidus Second problem is that the majority of these uniforms do _not_ have jumpskirt variants, I'm more than happy to throw the tag on so Harpies can wear them though.
> 
> With the Vox rework maybe you could use displacement maps to make skirt / harpie variants but 🤷

We'll keep the tag off. Wizmerge is getting Displacement maps, so I can try to get that setup for Harpies(Although I am incredibly distasteful of it)

**Comment by DangerRevolution** [comment]
Most likely worth considering adding tags to hide hair to some of these; I'm not sure if they look this bad in vanilla, but a lot of hairstyles just overflow the helmets.

**Comment by DangerRevolution** [comment]
Barebones ready for review; I'll slowly chip away at the common role items that aren't directly job related (such as Aprons or Shoes) if Aurora has fitting sprites. 

Main thing missing is the Botany headband; however I either need to completely remove flipping from it, find a sprite, or draw my own.

**Comment by VMSolidus** [comment]
I think I would strongly prefer if this PR was adding new clothing items using said textures, rather than fully replacing pre-existing clothing items. That'll go over with the players a hell of a lot better. 

image

**Comment by DangerRevolution** [comment]
> I think I would strongly prefer if this PR was adding new clothing items using said textures, rather than fully replacing pre-existing clothing items. That'll go over with the players a hell of a lot better.
> 
> image

I wasn't aware EE hosted servers, but I can do that

**Comment by DangerRevolution** [comment]
readded wizden variants of uniforms @VMSolidus

**Review by VMSolidus — APPROVED** [review]

**Pull request merged**
