### PR TITLE
Mass Engine Update

### PR DESCRIPTION
**Pull request by sleepyyapril**
# Description

An attempt to do all engine updates in one go. Not focusing on content associated, only what's needed for it to run and any bug fixes.

---

# TODO

- [x] Fix bug where unbuckling resets you to lying down.
- [x] Fix bug where you can no longer get up after lying down.
- [x] See what else I broke.
---

### CODE REVIEW

**Comment by sleepyyapril** [comment]
Please add Do Not Merge label!

**Comment by sleepyyapril** [comment]
I have run into a problem I do not know how to fix. Woe.

**Comment by FoxxoTrystan** [comment]
OH LORD...

ENGINES UPDATES.... ITS AGONY.

**Comment by VMSolidus** [comment]
By request, I have implemented https://github.com/space-wizards/space-station-14/pull/26238
in this PR.

**Comment by VMSolidus** [comment]
Now includes https://github.com/space-wizards/space-station-14/pull/28541
and https://github.com/space-wizards/space-station-14/pull/28291

**Comment by VMSolidus** [comment]
Mfw the linter fail is in a system that I'm the Codeowner of.

**Comment by VMSolidus** [comment]
Added this to the PR:
https://github.com/space-wizards/space-station-14/pull/27933

This is going to break several EE-specific systems, which now need to be fixed...

**Comment by gluesniffler** [comment]
> Added this to the PR: [space-wizards/space-station-14#27933](https://github.com/space-wizards/space-station-14/pull/27933)
> 
> This is going to break several EE-specific systems, which now need to be fixed...

i actually needed this, godspeed funny birb man

**Comment by sleepyyapril** [comment]
> > Added this to the PR: [space-wizards/space-station-14#27933](https://github.com/space-wizards/space-station-14/pull/27933)
> > This is going to break several EE-specific systems, which now need to be fixed...
> 
> i actually needed this, godspeed funny birb man

I'm actively make it work, you should likely wait until it does.

**Comment by VMSolidus** [comment]
Holy shit it's actually ready to merge.

**Comment by sleepyyapril** [comment]
We're not done yet.

**Comment by sleepyyapril** [comment]
#1227 has stable

**Comment by sleepyyapril** [comment]
Do not merge this or #1227 until truly stable.

**Comment by Aidenkrz** [comment]
>  Fix bug where unbuckling resets you to lying down.
> Fix bug where you can no longer get up after lying down.
Just port goob laying down
> Transfer old rules to guidebook.
Just port delta v's update, since the current rules are just delta's anyway

**Comment by DEATHB4DEFEAT** [comment]
> Just port delta v's update, since the current rules are just delta's anyway

#1154

**Comment by sleepyyapril** [comment]
The face of a girl who now has to 237.1.0-ify the entirety of shitmed.

_screams_

**Comment by Erisfiregamer1** [comment]
> The face of a girl who now has to 237.1.0-ify the entirety of shitmed.
> 
> _screams_

You opted into the 72 hells by making this pull request, have fun engine-updating Shitmed! :)

**Comment by sleepyyapril** [comment]
> > The face of a girl who now has to 237.1.0-ify the entirety of shitmed.
> > _screams_
> 
> You opted into the 72 hells by making this pull request, have fun engine-updating Shitmed! :)

It wasn't that bad, to be honest! 230 was hell, though.

**Comment by sleepyyapril** [comment]
Added:
- https://github.com/space-wizards/space-station-14/pull/30579
- https://github.com/space-wizards/space-station-14/pull/28484
- https://github.com/space-wizards/space-station-14/pull/31375

**Comment by sleepyyapril** [comment]
Mergeable...

**Review by VMSolidus — APPROVED** [review]
Alright let's fucking go.

**Pull request merged**
