### PR TITLE
New Trait: Liquor Lifeline 🍺🩹

### PR DESCRIPTION
**Pull request by angelofallars**
# Description

**Liquor Lifeline** 🍺 is a new trait (-3 points) that makes you slowly heal Brute and Burn (except Caustic) damage when drunk, healing more the drunker you are. Inspired by the SS13 /tg/station quirk called Drunken Resilience.

Strength of Liquor Lifeline healing in terms of its Brute damage healed per tick compared to Bicaridine:
- 0.1u to 0.5u Ethanol - 10% Bicaridine
- 0.5u to 7u Ethanol - 20% Bicaridine
- 7u to 11u Ethanol - 40% Bicaridine
- 11u to 15u Ethanol - 80% Bicaridine
- 15u+ Ethanol **(drunk poisoning starts)** - 120% Bicaridine

## Media

**Trait entry**

image

# Changelog

:cl: Skubman
- add: Add Liquor Lifeline (-3 points), a new positive trait that makes you slowly heal Brute and Burn damage when drunk, healing more the drunker you are. The trait also gives you the benefits of Alcohol Tolerance.
- tweak: The cost of the Alcohol Tolerance trait has been reduced from -2 points to -1 point.
- add: Dwarves receive the Liquor Lifeline trait for free.

### CODE REVIEW

**Review by DangerRevolution — APPROVED** [review]

**Comment by angelofallars** [comment]
After some discussion, I think it'd be good to reduce the cost of both this trait and Alcohol Tolerance. Alcohol Tolerance should have a lower cost since being able to drink more alcohol on its own does not provide any meaningful mechanical advantage.

**Comment by DangerRevolution** [comment]
should dwarves have this base?

**Comment by angelofallars** [comment]
> should dwarves have this base?

Sure, why not

**Comment by VMSolidus** [comment]
image

**VISIBLE CONFUSION**

**Review by VMSolidus — APPROVED** [review]

**Pull request merged**
