### PR TITLE
Add Localization for Senior Physician and Senior Engineer

### PR DESCRIPTION
**Pull request by zelezniciar1**
# Description

Adds localization for the Senior Engineer and Senior Physician roles that were recently enabled.

---

# TODO

n/a

---

<details><summary><h1>Media</h1></summary>
<p>

Snímka obrazovky 2024-12-01 164702
Snímka obrazovky 2024-12-01 165626

</p>
</details>

---

# Changelog

:cl: zelezniciar
- fix: Fixed Senior Engineer and Physician names not appearing correctly

### CODE REVIEW

**Review by sleepyyapril — APPROVED** [review]

**Comment by sleepyyapril** [comment]
@VMSolidus If this was not intended, this is a thing by the way. You can join as Senior roles now.

**Comment by sleepyyapril** [comment]
> Also, I'm pretty sure the testfail is unrelated?

It is!

**Comment by VMSolidus** [comment]
> @VMSolidus If this was not intended, this is a thing by the way. You can join as Senior roles now.

No it's intended, they're actually supported by loadouts now. Although not every map has them yet.

**Comment by sleepyyapril** [comment]
Okay, approve so we fix the silly locale issue lmao.

Also, what would it take to add alternate titles?

**Review by VMSolidus — APPROVED** [review]

**Pull request merged**
