### PR TITLE
Fix This Stupid Behavior

### PR DESCRIPTION
**Pull request by VMSolidus**
image

I don't need to explain this further. The image speaks for itself.

:cl:
- tweak: Cargo Technicians and Salvage Techs can now process cargo orders. You don't need to smash the fucking LO Locker with a pickaxe anymore.

### CODE REVIEW

**Comment by FoxxoTrystan** [comment]
At least gives this a correct changlog and information.

**Comment by VMSolidus** [comment]
> At least gives this a correct changlog and information.

Done

**Review by FoxxoTrystan — APPROVED** [review]
Personnaly im good with this.

Tho some orders, like security things should require LO/Warden approval, but thats depands on the code is done.

Because its way easy to just get stuff and then break it.

**Comment by VMSolidus** [comment]
> Personnaly im good with this.
> 
> Tho some orders, like security things should require LO/Warden approval, but thats depands on the code is done.
> 
> Because its way easy to just get stuff and then break it.

I want to start transitioning maps away from having the ATS, because it'll help alleviate some of the "Cargo/Salvage Toxicity". Saltern is a model for this. If a Station has the TradeStationComponent, and Cargo Pallets, cargo will work just fine on it without the ATS at all. My reasoning is such:

image

image

**Review by OldDanceJacket — APPROVED** [review]

**Comment by DangerRevolution** [comment]
Why aren't LRP changes like #1171 and this #1177 not kept to Deepstation and instead PRed here? EE is designed to be an MRP-HRP fork.

**Comment by FoxxoTrystan** [comment]
> > Personnaly im good with this.
> > Tho some orders, like security things should require LO/Warden approval, but thats depands on the code is done.
> > Because its way easy to just get stuff and then break it.
> 
> I want to start transitioning maps away from having the ATS, because it'll help alleviate some of the "Cargo/Salvage Toxicity". Saltern is a model for this. If a Station has the TradeStationComponent, and Cargo Pallets, cargo will work just fine on it without the ATS at all. My reasoning is such:
> 
> image
> 
> image

Im not a fan of this at all.
This makes cargo just... not cargo really.

Theres a CVar regarding ATS/Cargo Shuttle, lets servers uses this instead.

**Comment by VMSolidus** [comment]
> Why aren't LRP changes like #1171 and this #1177 and your desire to remove ATS not kept to Deepstation and instead PRed here? EE is designed to be an MRP-HRP fork.

How about you explain what your thought process is behind this? Because in my mind, all our damn servers are Lowpop, and on Lowpop servers, every fucking round, salvage takes a pickaxe to the LO Office to steal his ID and digiboard so that they can hoard everything in the salvage ship. How the fuck is that not NRP?

**Comment by Mnemotechnician** [comment]
> How about you explain what your thought process is behind this? Because in my mind, all our damn servers are Lowpop, and on Lowpop servers, every fucking round, salvage takes a pickaxe to the LO Office to steal his ID and digiboard so that they can hoard everything in the salvage ship. How the fuck is that not 

"All our damn servers"? Please, let me interject for a second and recite one of the core ideals of Einstein-Engines...

> No official servers will ever be made for Einstein-Engines.

> In order to prevent a potential conflict of interest, we will never open any server directly using the Einstein Engines codebase itself. Any server claiming to be an official representation of this fork is not endorsed in any way by this organization. We however would like to invite anyone wishing to create a server to make a fork of Einstein Engines.

Okay, I'm not insane, and EE still doesn't officially have any official servers, and is still supposed to provide the best experience regardless of what is the average population on deepstation.

Back to the point,

> every fucking round, salvage takes a pickaxe to the LO Office to steal his ID and digiboard so that they can hoard everything in the salvage ship. How the fuck is that not NRP?

It IS NRP and a bad example of pwoergaming. if salvage does that, the admins should take action. Send a centcom inspector, blow up their ship, bwoink the salvagers if it is a consistent issue. Roleban if they do not change. We should NOT, by any means NOT endorsing NRP behavior. Encouraging NRP/LRP behavior is what we all hated about wizden, we shouldn't do that ourselves.

**Comment by Mnemotechnician** [comment]
> Hey look, an untouched LO office post this update.

Lets not repeat the mistake of wizden and try to have a constructive discussion instead.

**Comment by DangerRevolution** [comment]
> Because in my mind, all our damn servers are Lowpop

EE doesn't host servers?

And several servers (Goob 2, Floof, Lost Paradise) aren't lowpop either.

And lowpop provisions for this by giving Cargo Techs orders access on skeleton crew to negate this problem.

> and on Lowpop servers, every fucking round, salvage takes a pickaxe to the LO Office to steal his ID and digiboard so that they can hoard everything in the salvage ship. How the fuck is that not NRP?

It's NRP, which isn't your concern (EE doesn't host servers), it's the concern of the maintainers of the downstreams which are lowpop and allow for LRP behaviour.

A better solution could be... removing all the hour requirements for roles (and letting downstreams set them up) so it doesn't take 30-40 hours of gameplay for command roles with orders access (excluding CT which has orders on lowpop)

**Comment by Mnemotechnician** [comment]
> And lowpop provisions for this by giving Cargo Techs orders access on skeleton crew to negate this problem.

I agree with this, we can add Orders to the list of cargo technicians' and salvagers' ExtendedAccess. That would both solve the issue that caused this spite PR, and adhere to the higher roleplay standards. Engineers, for instance, already get atmos access in low-pop for a similar reason: so they don't have to break into atmos to save the station from suffocating.

**Pull request merged**
