### PR TITLE
Make Jobs & Antags Use CharacterRequirements

### PR DESCRIPTION
**Pull request by DEATHB4DEFEAT**
# Description

- Makes jobs use CharacterRequirements
- Makes antags use CharReqs
- Splits CharReqs into multiple files
- Adds a Whitelist CharReq
- Prays the tests pass

---

### CODE REVIEW

**Comment by DEATHB4DEFEAT** [comment]
Tests are not having a good time.

**Comment by VMSolidus** [comment]
image

Running tests locally, here's what I got so far.

**Comment by VMSolidus** [comment]
image
Looks like this needs to be changed to REPLICATED, so that the requirements system is allowed to use it clientside. Client has no way of knowing this CCVar exists otherwise. Weird that it wasn't REPLICATED before, since Shared Code can't use SERVERONLY Cvars for this very reason, unless you run it under _net.IsServer.

**Comment by VMSolidus** [comment]
Oh the tests aren't running because REQUIRES was included in the description lmao.

**Comment by VMSolidus** [comment]
So it turns out the REQUIRES thing in tests is somehow expecting that, "THIS PR REQUIRES ROBUST TOOLBOX PR 595".

**Comment by DEATHB4DEFEAT** [comment]
> So it turns out the REQUIRES thing in tests is somehow expecting that, "THIS PR REQUIRES ROBUST TOOLBOX PR 595".

wtf lol

**Comment by DangerRevolution** [comment]
Can you clarify a little more on what this PR does?

I think I understand what it does, and it's kind of wild if I understand it correctly

**Comment by DEATHB4DEFEAT** [comment]
> Can you clarify a little more on what this PR does?
> 
> I think I understand what it does, and it's kind of wild if I understand it correctly

Jobs used to use JobRequirements, now they use CharacterRequirements

**Comment by DangerRevolution** [comment]
> > Can you clarify a little more on what this PR does?
> > I think I understand what it does, and it's kind of wild if I understand it correctly
> 
> Jobs used to use JobRequirements, now they use CharacterRequirements

is CharacterRequirements slot-based?

**Comment by DEATHB4DEFEAT** [comment]
> > > Can you clarify a little more on what this PR does?
> > > I think I understand what it does, and it's kind of wild if I understand it correctly
> > 
> > 
> > Jobs used to use JobRequirements, now they use CharacterRequirements
> 
> is CharacterRequirements slot-based?

huh?

**Comment by DangerRevolution** [comment]
What's character requirements?

**Comment by DEATHB4DEFEAT** [comment]
> What's character requirements?

The things loadouts and traits use.

**Comment by DangerRevolution** [comment]
> > What's character requirements?
> 
> The things loadouts and traits use.

Really?

**Comment by VMSolidus** [comment]
> Can you clarify a little more on what this PR does?
> 
> I think I understand what it does, and it's kind of wild if I understand it correctly

This PR is essentially changing Jobs, Antags, Loadouts, and Traits to all share a combined, **Unified** Character Requirements System, where before Jobs and Antags had their own separate system. Now you can modularly whitelist and blacklist Jobs + Antags to the same extreme degree of flexibility that you can with Loadouts. It combines Job & Antag requirements with several features that are extremely often requested from our Downstreams, such as Species, Age, Sex, Trait Selections, and so on. For instance, you can now declare that the Captain cannot have the Blind Trait, and/or must be greater than 30 years of age, and so on.

**Review by VMSolidus — APPROVED** [review]

**Comment by DEATHB4DEFEAT** [comment]
> you can now declare that the Captain cannot have the Blind Trait

BP

**Comment by VMSolidus** [comment]
> > you can now declare that the Captain cannot have the Blind Trait
> 
> BP

RIP Adym Ryuzo, presuming that any of our downstreams actually use this system to do that. Although a decent chunk of them might. It was a really common complaint from Hosts that there was nothing in the game that stopped people from spawning in as a Captain or HOS with 5+ disabilities, and then ending up with a character that was just a poor taste joke.

**Comment by DangerRevolution** [comment]
So um, what new things can roles discriminate by using character reqs?

**Comment by VMSolidus** [comment]
> So um, what new things can roles discriminate by using character reqs?

>Age
>Sex
>Playtime
>Whitelist
>Species
>Traits(Or Lack Of)
>Backpack Preference
>Pants vs. Skirt
>How long you have played overall
>How long you have played a specific department
>How long you have played a specific character
>Having a Loadout Item
>INVERTED Versions of all of these.

**Comment by VMSolidus** [comment]
> > So um, what new things can roles discriminate by using character reqs?
> 
- Age
- Sex
- Playtime
- Whitelist
- Species
- Traits(Or Lack Of)
- Backpack Preference
- Pants vs. Skirt
- How long you have played overall
- How long you have played a specific department
- How long you have played a specific character
- Having a Loadout Item
- INVERTED Versions of all of these.

**Review by DangerRevolution — APPROVED** [review]

**Pull request merged**
