### PR TITLE
Transhumanism Physical Traits

### PR DESCRIPTION
**Pull request by VMSolidus**
# Description

This PR adds several new "High Cost Physical Traits", that each follows a theme of Transhumanism. Bionic augmentations that provide the user some benefit, typically at a very high cost.

<details><summary><h1>Media</h1></summary>
<p>

image

image

image

image

</p>
</details>

# Changelog

:cl:
- add: Added 8 new Physical Traits. These are, Cyber-Eyes Basic System(Plus 4 different modular options), Bionic Arm, Dermal Armor, and Platelet Factories.

### CODE REVIEW

**Comment by DangerRevolution** [comment]
How is a player meant to know that someone magically has non-flashable eyes? Or they can heal themselves out of combat?

**Comment by XavierSomething** [comment]
I'm a little worried about adding these in regards of in case if "The Surgery Update™" ever releases, then it could mess with things with having these traits around. Although I know that update will likely not come out for a very long time, but good to consider if we ever do have to consider that far in terms of consequences.

**Comment by Remuchi** [comment]
> I'm a little worried about adding these in regards of in case if "The Surgery Update™" ever releases, then it could mess with things with having these traits around. Although I know that update will likely not come out for a very long time, but good to consider if we ever do have to consider that far in terms of consequences.

when surgery update finally comes around these traits can be easily swapped to change players eyes/whatever to corresponding implants/transplants/whatever

**Comment by VMSolidus** [comment]
> I'm a little worried about adding these in regards of in case if "The Surgery Update™" ever releases, then it could mess with things with having these traits around. Although I know that update will likely not come out for a very long time, but good to consider if we ever do have to consider that far in terms of consequences.

Completely irrelevant. I don't give a fuck what Wizden is working on, and will not consider any "Theoretical Future Updates", especially ones that are in perpetual development hell, as a factor in what I am making *today*. Surgury will likely never come out at the current pace.

**Comment by DangerRevolution** [comment]
Is there a reason Cyber Eyes has no interactions with penlights?

**Comment by VMSolidus** [comment]
I've updated this PR so that all of the "Bionics Traits" all have a Prisoner blacklist. This operates on the same Shadowrun logic where people with "Potentially dangerous implants" have them surgically removed and placed in cold storage if they go to prison.

**Comment by VMSolidus** [comment]
> Is there a reason Cyber Eyes has no interactions with penlights?

That would be super bloaty? And there's not really any reason that sufficiently advanced Cybereyes should have any different interactions with a penlight if they're trying to imitate human eyes.

**Comment by DangerRevolution** [comment]
> > Is there a reason Cyber Eyes has no interactions with penlights?
> 
> That would be super bloaty? And there's not really any reason that sufficiently advanced Cybereyes should have any different interactions with a penlight if they're trying to imitate human eyes.

How will a player be able to tell that another player is unflashable?

**Comment by VMSolidus** [comment]
> > > Is there a reason Cyber Eyes has no interactions with penlights?
> > 
> > 
> > That would be super bloaty? And there's not really any reason that sufficiently advanced Cybereyes should have any different interactions with a penlight if they're trying to imitate human eyes.
> 
> How will a player be able to tell that another player is unflashable?
> 
> This is considered normally with sprites for sunglasses & shades being prominent.

I can probably add a component specific to these traits that does a PushMarkup when shift-click examining someone. Which adds some unique flavor text indicating that their eyes are modified.

**Comment by DangerRevolution** [comment]
As a general point; these are all pretty strong, powerful traits with no way to know someone has one until it's too late.

**Review by Peptide90 — APPROVED** [review]
Last comment is good. Examine text would be a minimum I’d say.

**Comment by VMSolidus** [comment]
> Last comment is good. Examine text would be a minimum I’d say.

Yea I'll make sure to make those admittedly super simple components before this PR is merged.

**Review by DEATHB4DEFEAT — APPROVED** [review]

**Pull request merged**
