### PR TITLE
Ports Shitmed Updates From Goob

### PR DESCRIPTION
**Pull request by gluesniffler**
Lots of stuff. Also moved everything I could to the _Shitmed namespace as I do in Goob. Will make future ports way faster

# Changelog
:cl: Mocho
- add: Added some fun organs and other thingies, check out the Goob PRs if you want more details.
- fix: Fixed tons of issues with shitmed. Too many for the changelog in fact.

### CODE REVIEW

**Comment by Eagle-0** [comment]
@coderabbitai review

**Comment by Eagle-0** [comment]
:trollface:

**Comment by Eagle-0** [comment]
oh wait this is einstien engines

**Review by VMSolidus — DISMISSED** [review]
Excellent, I was excitedly waiting for this port to be finished. Good thing this makes keeping parity and updates easier.

**Comment by sleepyyapril** [comment]
bro got the chairs failing!!

**Comment by gluesniffler** [comment]
> bro got the chairs failing!!

epic n14 port fail

**Review by VMSolidus — APPROVED** [review]
I love how the stupid map assets accidentally added a new heisentest. We're back up to 2 heisentests again.

**Review by sleepyyapril — APPROVED** [review]

**Pull request merged**
