### PR TITLE
Key Auth / MV Engine

### PR DESCRIPTION
**Pull request by Skyedra**
# Description

Replaces wizden RT engine with MV engine fork.  

Not sure if anyone is interested in it, but if so, using this PR or merging from the associated ee example integration repo should save a lot of the [manual merge steps](https://spacestationmultiverse.com/how-to-switch-to-mv-engine/) versus porting from ssmv content repo directly.  

Features:
* Key auth
* (Optional) VPN blocker
* SCSI Disabled by Default

[More information on MV Engine web page](https://spacestationmultiverse.com/mv-engine/)

There is a specific backport branch of MV Engine for EE-based forks, currently [April2024](https://github.com/Space-Station-Multiverse/RobustToolbox/commits/April2024/).  It includes the new MV features + the image sharp version number upgrade backport.

Please read the 'Drawbacks' section to see if tradeoffs of using MV is right for your fork.  It means your server will not be accessible from WizDen launcher, so consider carefully.  Projects using postgres should test this before deployment as I don't use postgres.

# Changelog

:cl: Skye
- add: MV Engine / Key Auth

### CODE REVIEW

**Comment by FoxxoTrystan** [comment]
So this PR is here not to merged with EE but cherry-picked for forks thats want it?

**Comment by DEATHB4DEFEAT** [comment]
I like what you've done, but for now we will not accept this, so I will close this.
We will keep this in mind for if we ever are ready/need to switch engines.

**Comment by Skyedra** [comment]
FYI I updated this branch yesterday with the latest MV version

EE servers affected by the dehub are welcome on MV :)

**Comment by DEATHB4DEFEAT** [comment]
yippee

**Pull request closed without merging**
