### PR TITLE
Grabintent

### PR DESCRIPTION
**Pull request by Eagle-0**
Adds the throwing system, I'm too tired to do a proper desc right now

### CODE REVIEW

**Comment by Eagle-0** [comment]
HOLY FUCK WHAT

**Comment by Eagle-0** [comment]
wrong repo :anguish:

**Comment by VMSolidus** [comment]
> wrong repo :anguish:

image

**Comment by VMSolidus** [comment]
NO, BY ALL MEANS, PR IT HERE. THAT SHIT'S FUCKING COOL.

**Comment by Eagle-0** [comment]
> NO, BY ALL MEANS, PR IT HERE. THAT SHIT'S FUCKING COOL.

I probably don't have permission, you'd have to ask W-WD

**Pull request closed without merging**
