### PR TITLE
Radiation Doesn't Prevent DoAfters

### PR DESCRIPTION
**Pull request by VMSolidus**
# Description

I got so pissed off that being near a singularity means you can't crowbar doors, that shortly after dying to a singularity because of said bullshit, I had written this before an emergency shuttle even arrived to pick up the crew. 

# Changelog

:cl:
- fix: Radiation damage no longer interrupts DoAfters.

### CODE REVIEW

**Review by DEATHB4DEFEAT — APPROVED** [review]

**Comment by beck-thompson** [comment]
Shouldn't this also stop cold / heat damage? Seems like the same damage "type" if you know what I mean.

**Comment by beck-thompson** [comment]
Mind telling me why this is a bad idea? It makes sense to me but two thumbs down tells me I must be missing something!

**Comment by VMSolidus** [comment]
> Mind telling me why this is a bad idea? It makes sense to me but two thumbs down tells me I must be missing something!

So it's not necessary with cold because there's zero sources of cold damage in the game that deal enough damage in a single tick to interrupt do-afters. Fire damage I actually agree that it should because it's something "Sufficiently disruptive and avoidable" that getting caught by fire is genuinely your own fault. Radiation damage is completely invisible, with no feedback, and no indication at all of what's going on. Lord Singuloth can be completely offscreen, and still prevent you from crowbarring doors to get away from him. Supermatter can also get radioactive enough to interrupt do-afters from literally the opposite side of the station.

**Comment by beck-thompson** [comment]
Mostly makes sense! Thanks for the response! I felt a little bad after the two thumbs down 😆

**Review by DangerRevolution — DISMISSED** [review]
Changelog doesn't accurately represent PR

**Comment by VMSolidus** [comment]
> Changelog doesn't accurately represent PR

You are a monster.

**Review by DangerRevolution — APPROVED** [review]
Not even evil, radiation just exists in more scenarios than Singulo

**Pull request merged**
