### PR TITLE
Shitmed Update 2 - [Insert Snarky Remark]

### PR DESCRIPTION
**Pull request by gluesniffler**
# Description
image

Honey wake up, another shitmed PR with 5 features and a trillion bugs! I love bloat.

---

# Known Bugs
- A lot of shit with changelings lol
- Markings suddenly disappear from your entity apparently at random. Wizden exclusive issue as of now.
- Fire heretics explode when ascending due to part damage shitcode (sorry)
- Some exceptions/null point references at round end, tentatively related to salvage corpses.
- Slots having wonky behavior due to not being networked. More of a broad issue with how I implemented them initially.
- Arachne are FUCKED with surgery, I was incredibly tempted to set them to roundstart: false, but I'll try to hotfix it this week.

---

# Changelog

:cl: Mocho, Deltanedas
- add: Ported Ghetto Surgery from Deltanedas!
- add: Ported fishops organs from Deltanedas!
- add: Added different step durations to each surgery step.
- add: Added a T2 research for advanced surgical tools
- add: Added a T3 research for an omnitool for surgery.
- add: Added Surgical and Advanced Surgical modules for Mediborgs
- add: Mediborgs can now perform surgery!
- add: Added lobotomies as an operation. Godspeed you psychopaths.
- add: Added cybernetic arms, legs and eyes.
- add: Added EMP weaknesses to all cybernetic parts (the day of reckoning will come for IPCs soon)
- add: Losing your eyes now blinds you.
- fix: Fixed a few species that did not inherit from BasePart's, thus taking damage types they shouldn't on their limbs.
- fix: Fixed harpy lungs not being usable in surgeries.
- fix: Fixed biosynthetic and other printable parts not allowing you to attach body parts to them. 
- fix: Fixed fire being able to destroy your chest.
- fix: Fixed entities being able to take over your body by just inserting a brain or another head on top of you.
- fix: Fixed some shitcode that didnt let rejuvenate or godmode work properly.
- fix: Fixed bionic arm, and cybernetic eyes traits not working properly due to shitty networking.
- tweak: Increased tend wounds's speed by double, and bumped up the values on its calculations. DEATH TO TOPICALS, LEAVE THOSE TO TIDERS.
- tweak: Beheading an entity now doesnt let it move, speak, and forces it to the ground immediately (literally 1984!!11!!)
- tweak: Changed sprites on most surgical tools to now use /tg/ sprites.
- tweak: Unbound shitmed targeting doll keybinds by default (did you know we have those).

### CODE REVIEW

**Comment by gluesniffler** [comment]
Think thats a heisentest? Previous commit had passed all tests.

**Comment by Tmanzxd** [comment]
Test fail real: Can't resolve "Content.Shared.Body.Components.BodyComponent" on entity  (13796/n13796)!

**Comment by sleepyyapril** [comment]
> Test fail real: Can't resolve "Content.Shared.Body.Components.BodyComponent" on entity (13796/n13796)!

Did you not check the new tests, silly?

**Comment by sleepyyapril** [comment]
No test fails

**Review by sleepyyapril — APPROVED** [review]

**Review by Erisfiregamer1 — APPROVED** [review]
As the C# Person for Arcadis I can say with a confidence of 0.01% that this fixes less bugs than it introduces.

**Comment by sleepyyapril** [comment]
> As the C# Person for Arcadis I can say with a confidence of 0.01% that this fixes more bugs than it introduces.

sick, merge it immediately!!

**Comment by Erisfiregamer1** [comment]
> > As the C# Person for Arcadis I can say with a confidence of 0.01% that this fixes more bugs than it introduces.
> 
> sick, merge it immediately!!

i stand by this statement (we moved fast and broke stuff, now we need to fix what broke)

**Comment by sleepyyapril** [comment]
> > > As the C# Person for Arcadis I can say with a confidence of 0.01% that this fixes more bugs than it introduces.
> > 
> > 
> > sick, merge it immediately!!
> 
> i stand by this statement (we moved fast and broke stuff, now we need to fix what broke)

no, i want more bugs. in fact, revert all fixes!

**Review by VMSolidus — APPROVED** [review]
Even more fun. Well let's get these bugs fixed.

**Comment by Tmanzxd** [comment]
> > Test fail real: Can't resolve "Content.Shared.Body.Components.BodyComponent" on entity (13796/n13796)!
> 
> Did you not check the new tests, silly?

was the fails from 4 hours before that comment irrelevant now lol

**Comment by rbertoche** [comment]
Nice.
Just that :P

**Review by OldDanceJacket — APPROVED** [review]

**Pull request merged**
