### PR TITLE
Mirror: Make parrots talk like parrots

### PR DESCRIPTION
**Pull request by SimpleStation14**
###### `cd4eda44b88a75d7498efca42c464dd4c73c5684`

PR opened by <a href="https://github.com/Tayrtahn"> Tayrtahn</a> at 2024-03-22 17:22:18 UTC

---

PR changed 8 files with 168 additions and 0 deletions.

The PR had the following labels:

---

<details open="true"><summary><h1>Original Body</h1></summary>

> 
> 
> 
> ## About the PR
> 
> In the rare cases that parrot become controlled by players, they now sound a bit more parrot-y.
> 
> - Added the parrot squawk sound as a speech sound, so they no longer speak silently.
> - Gave parrots a speech verb set, so they "squawk", "tweet", and "chirp" their messages, instead of just "say"-ing them.
> - Parrots can "scream" now (which just plays the squawk sound).
> - Parrots have their own accent that gets applied to everything they say! It adds some random squawks to the beginnings and ends of messages. Sometimes they repeat the longest word in a message. RAAWK! Sometimes!
> 
> ## Why / Balance
> 
> There are a lot of animals, but very little that sets them apart from each other. This makes parrots a little more interesting (though there's plenty more to be done).
> 
> And no, I've never seen a player-controlled parrot in the game either. But it could happen! And when it does, now it'll be cooler.
> 
> ## Technical details
> 
> Added a few components to the parrot entity prototype, and made EmoteSounds, SpeechSounds, and SpeechVerb for parrots.
> 
> Added ParrotAccentComponent/System, which handle the accent.
> 
> ## Media
> 
> 
> https://github.com/space-wizards/space-station-14/assets/85356/a863f384-8244-4d03-b9bb-2c0394b44488
> 
> Sorry for the lack of audio; blame Apple. There are squawking noises whenever the parrot chats or screams.
> - [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> ## Breaking changes
> 
> 
> **Changelog**
> 
> 
> 
> :cl:
> - add: Parrots now sound more like parrots when they talk. RAWWK!

</details>

### CODE REVIEW

**Review by FoxxoTrystan — COMMENTED** [review]
This is good.

But i wounder how exactly its will function with Languages, Meaning i have to make a Parrot/Bird Language and make it able to speak GC?

Thats a problem for Language PR, not this PR but so far This PR is good!

**Comment by DangerRevolution** [comment]
> This is good.
> 
> But i wounder how exactly its will function with Languages, Meaning i have to make a Parrot/Bird Language and make it able to speak GC?

Not necessary, up to you really, the *System* of Languages is the important part, the actual yml languages can be done after the fact. Up to you really though.

**Comment by FoxxoTrystan** [comment]
> > This is good.
> > But i wounder how exactly its will function with Languages, Meaning i have to make a Parrot/Bird Language and make it able to speak GC?
> 
> Not necessary, up to you really, the _System_ of Languages is the important part, the actual yml languages can be done after the fact. Up to you really though.

This can be handle easly later.
and is a issue for Languages PR, when this PR is merged i will make a new commit on Language to correctly handle this PR.

**Review by DangerRevolution — APPROVED** [review]
As an accent system, is fine.

**Review by VMSolidus — APPROVED** [review]

**Pull request merged**
