### PR TITLE
Mirror: Adds "untriaged" labeler workflow

### PR DESCRIPTION
**Pull request by SimpleStation14**
###### `0303e9cb36902007354e9a5ed9fbc147c9ebe70f`

PR opened by <a href="https://github.com/PJB3005"> PJB3005</a> at 2024-03-24 17:17:08 UTC

---

PR changed 1 files with 13 additions and 0 deletions.

The PR had the following labels:
- No C#

---

<details open="true"><summary><h1>Original Body</h1></summary>

> All new opened issues automatically get marked as "untriaged", so a maintainer can go through them properly.
> 

</details>

### CODE REVIEW

**Review by VMSolidus — APPROVED** [review]

**Comment by FoxxoTrystan** [comment]
Not gona approved anything as this is not my thing!
good luck!

**Comment by stellar-novas** [comment]
This is for issues, not PRs. It's for maintainers to easily find which issues haven't been looked at/claimed by a dev.

**Comment by DEATHB4DEFEAT** [comment]
> This is for issues, not PRs. It's for maintainers to easily find which issues haven't been looked at/claimed by a dev.

Add the needs review label to issues ¯\_(ツ)_/¯

**Review by Pspritechologist — CHANGES_REQUESTED** [review]
Name seems unclear to me. If the intention is for 'unclaimed' Issues, why not simply use 'Unclaimed?'
I will say that it seems like a useful distinction to 'Needs Review.' You'd filter by the two for very different reasons

**Comment by DEATHB4DEFEAT** [comment]
> If the intention is for 'unclaimed' Issues, why not simply use 'Unclaimed?'

image

**Pull request closed without merging**
