### PR TITLE
New Trait: Sign Language

### PR DESCRIPTION
**Pull request by angelofallars**
# Description

**Sign Language** is a 1-point Visual trait that allows you to use Galactic Sign Language.

## Media

image

image

# Changelog

:cl: Skubman
- add: Add a new 1-point trait called Sign Language, a trait that allows you to communicate in Galactic Sign Language.

### CODE REVIEW

**Comment by DangerRevolution** [comment]
This should probably also be reused for foreigner tbh; and just have translators in Loadouts but that's a wyci

**Review by DangerRevolution — APPROVED** [review]

**Review by DangerRevolution — CHANGES_REQUESTED** [review]
This doesn't add the trait to mute.

**Comment by angelofallars** [comment]
> This doesn't add the trait to mute.

Mute and Sign Language should be separate, as when you're a Mute you can still communicate with other methods, namely papers, and also Natural Telepath giving you access to telepathic chat.

**Review by DangerRevolution — APPROVED** [review]

**Review by VMSolidus — APPROVED** [review]
Finally.

**Comment by FoxxoTrystan** [comment]
Me lazy so someone else does it, nice.

**Pull request merged**
