### PR TITLE
Another Saltern Update

### PR DESCRIPTION
**Pull request by VMSolidus**
# Description

This update comes courtesy of the SiN Mapping Team.

- Added job roles Courier, Robotics
- Did small edits to every department.
- Made escape pod area better.
- New arrivals dock area. (Including Sec checkpoint)
- Fixed multiple bugs
- Reworked a lot of medical
- Moved Cryogenics.
- New station beacons.
- Removed ID computers from all command rooms except HOP
- All maints space windows buffed.

<details><summary><h1>Media</h1></summary>
<p>

image

image

</p>
</details>

# Changelog

:cl: SiN Mapping Team
- add: Another big update for Saltern

### CODE REVIEW

**Comment by Merrokitsune** [comment]
Mind posting the full image?

**Comment by VMSolidus** [comment]
> Mind posting the full image?

Map Painter is currently fucked last time I tried.

**Comment by Merrokitsune** [comment]
Ah, fiddlesticks.
At least, you can post screenshots of every department. I am curious at what changes did you do.

**Comment by VMSolidus** [comment]
> Ah, fiddlesticks. At least, you can post screenshots of every department. I am curious at what changes did you do.

I had no hand at all in this, it was done entirely by the SiN Mapping Team. I just happen to be the only person who can access the mapping server who knows how to make a github PR lmao.

**Review by OldDanceJacket — APPROVED** [review]

**Review by sleepyyapril — APPROVED** [review]

**Pull request merged**
