### PR TITLE
Glorious Tools!

### PR DESCRIPTION
**Pull request by FoxxoTrystan**
# Glorious Tools!

Add//Change a bunch of tools sprites that was in the tool category to make them fit better in general, Old TG... please update.exe

Anywho here they are!

---

# TODO

- [x] Import Sprites

---

<details><summary><h1>Media</h1></summary>
<p>

image

</p>
</details>

---

# Changelog

:cl:
- tweak: New Tools Sprites!

### CODE REVIEW

**Comment by stellar-novas** [comment]
Are 1 and 2 mistakes? On the screwdriver and seclite

**Comment by FoxxoTrystan** [comment]
> Are 1 and 2 mistakes? On the screwdriver and seclite

Oh ye those were template using it to edit.

**Comment by FoxxoTrystan** [comment]
Murder build again!

**Comment by VMSolidus** [comment]
It was the stupid mobMimic test. Like usual.

**Review by DangerRevolution — APPROVED** [review]

**Review by VMSolidus — APPROVED** [review]

**Pull request merged**
