### PR TITLE
Catch-Up Cherry Pick 1

### PR DESCRIPTION
**Pull request by DEATHB4DEFEAT**
# Description

I went from the next commit after the latest mirror to before 2db374988c.

---

# TODO

- [x] Figure out how to live update the editor dummy
- [x] Stop editor sliders lagging a ton
- [x] Fix runtime errors or whatever
- [x] Do some playtesting, see what happens
- ~~Pick more PRs~~

---

# Changelog

:cl:
- add: Merged ~250-500 WizDen PRs

### CODE REVIEW

**Comment by DEATHB4DEFEAT** [comment]
> There might be some missing...

They're almost all missing.
I found them though.

**Comment by DEATHB4DEFEAT** [comment]
There they are!

**Comment by DEATHB4DEFEAT** [comment]
I was gonna name this PR `Ketchup Cherry Pick 1`..

**Comment by stellar-novas** [comment]
remember not to squash merge!!

**Comment by DEATHB4DEFEAT** [comment]
I summon Solidus to fix the last few random lil errors for me.

**Comment by DEATHB4DEFEAT** [comment]
ejoftdsromgst

**Review by VMSolidus — APPROVED** [review]

**Pull request merged**
