### PR TITLE
Walls/Windows Resprites!

### PR DESCRIPTION
**Pull request by FoxxoTrystan**
# Walls/Windows Resprites!

Import the changes that i provided to frontier in PR: https://github.com/new-frontiers-14/frontier-station-14/pull/418 to EE, including part of this PR: https://github.com/new-frontiers-14/frontier-station-14/pull/757

Those Walls/Windows LOOK EXTREMLY MORE BETTER then the old TG walls/windows, Common its 2024!
We need DRIP IN ALL WALLS!

.yml changes are needed for connection to walls/window and prevent connected from doors, shutters, ect...

---

# TODO

- [x] Import Sprites.
- [x] yml changes

---

<details><summary><h1>Media</h1></summary>
<p>

image

</p>
</details>

---

# Changelog

:cl:
- tweak: Better wall sprites.
- tweak: Better window sprites.

### CODE REVIEW

**Review by VMSolidus — APPROVED** [review]
image

These are quite excellent!

**Comment by FoxxoTrystan** [comment]
> image
> 
> These are quite excellent!

Resrptires baby!
MORE INCOMING!
signaller
sec_headset

**Comment by FoxxoTrystan** [comment]
Debug being debug... nice.

**Review by DangerRevolution — APPROVED** [review]
needs to be merged after Engine PR

**Comment by DangerRevolution** [comment]
engine was fixed, turning on auto-merge

**Pull request merged**
