### PR TITLE
Replace Shittle With Pathfinder

### PR DESCRIPTION
**Pull request by VMSolidus**
# Description

Part 3 of my evil plan to make salvage not suck: Give them a fancy goody, but with a twist. This PR adds the Pathfinder Expedition Vessel from Frontier, which replaces the Shittle as the default salvage shuttle to spawn on each map. I have my own funky reasoning for this. The primary one being, "The Pathfinder is powered by an AME. This means salvage are REQUIRED to periodically return to the station to get fuel. It is impossible for them to refuel themselves away from the station."

It also, notably, spawns with an Expedition Console. More on that in a follow-up PR where I rework expeditions to work "More like Frontier". 

# TODO

<details><summary><h1>Media</h1></summary>
<p>

image

image

</p>
</details>

# Changelog

:cl:
- add: The Salvage Shittle has been replaced with the Pathfinder Expedition Vessel from Frontier.

### CODE REVIEW

**Comment by DEATHB4DEFEAT** [comment]
AME will be very annoying to listen to. Also are the consoles missing or is the map media more up to date than the game media?

**Comment by VMSolidus** [comment]
> AME will be very annoying to listen to. Also are the consoles missing or is the map media more up to date than the game media?

The first picture is a little out of date, they were hidden underneath tables, so I removed the tables. I also put in the salvage magnet and an ore processor. As far as the AME. Skill issue if it bothers you? Frontier players go entire 6 hour shifts with it in the background.

**Comment by DEATHB4DEFEAT** [comment]
> As far as the AME. Skill issue if it bothers you?

It's not a skill issue, it's also not much an issue at all though.

> Frontier players go entire 6 hour shifts with it in the background.

crazy

**Comment by VMSolidus** [comment]
Final version of the Pathfinder.

image

**Review by DEATHB4DEFEAT — APPROVED** [review]
increible

**Pull request merged**
