### PR TITLE
Ports Atmospheric Alerts Computer

### PR DESCRIPTION
**Pull request by zelezniciar1**
# Description

- Ports the Atmospheric Alerts Computer, as implemented on WizDen

---

# TODO

[x] small fixes

n/a

---

<details><summary><h1>Media</h1></summary>
<p>

Snímka obrazovky 2024-09-13
225958

</p>
</details>

---

# Changelog

:cl: zelezniciar
- add: Added Atmospheric Alerts Computer

### CODE REVIEW

**Comment by VMSolidus** [comment]
image

image

image


>Mfw
image

**Comment by DEATHB4DEFEAT** [comment]
> image

This could be *so much* smaller with a bit of pattern matching.

**Comment by VMSolidus** [comment]
Fuck it we should just leave this PR merged as-is, because I'm not about to open the can of worms that is "MERGE CONFLICT HELL" caused by cleaning up wizcode in the same PR that cherry-picks it.

**Review by VMSolidus — APPROVED** [review]

**Comment by FoxxoTrystan** [comment]
Ehh il make my  own review later.

But by god

**Comment by zelezniciar1** [comment]
I won't deny that it's shitcode, I can try and clean it up a bit, but...

**Review by OldDanceJacket — APPROVED** [review]

**Pull request merged**
