### PR TITLE
Cocoon Cleanup & Minor Bloodsucker Tweaks

### LINKED ISSUE #978: Oneirophag and maybe Arachne bug
# Description
Oneirophag cant cocoon those who on screen 1 and what with the sizes of cocoons? (Screen 2)

# Media
image
image

### PR DESCRIPTION
**Pull request by Aidenkrz**
# Description

- Generalizes cocooning
- Allows any mob to be cocooned
- Cocoon bloodsucking moved to vampirism system
- Any blood sucker can drink from cocoons
- Vampirism no longer fails if bloodstream isn't normal blood, but gives a pop up
- Vampirism `WebRequired` actually works in a way that makes sense
- Adds cocooning and bloodsucker to all spider mobs + Arachnids

resolves #978

---

# Changelog

:cl:
- tweak: All spiders, arachne, and arachnids can cocoon mobs, and drink their blood.

### CODE REVIEW

**Comment by FoxxoTrystan** [comment]
Oh ye, should make everyone to be cocoon, not those only with bloodstream or "this type of blood"

**Comment by Aidenkrz** [comment]
> Oh ye, should make everyone to be cocoon, not those only with bloodstream or "this type of blood"

So just let them cocoon any mob?

**Comment by FoxxoTrystan** [comment]
> > Oh ye, should make everyone to be cocoon, not those only with bloodstream or "this type of blood"
> 
> So just let them cocoon any mob?

Yeah or add some optional settings like tags, ect...

Should check if the target is a mob if yes cocoon.
*Biting/Feeding* is another system itself.

Also when this PR is finished its should be given to all spooders correctly.

**Review by FoxxoTrystan — APPROVED** [review]

**Review by VMSolidus — APPROVED** [review]
I have tested and verified that this actually works correctly. Thank you for this PR.

**Pull request merged**
