### PR TITLE
More Sec Loadout Guns

### PR DESCRIPTION
**Pull request by VMSolidus**
# Description

<details><summary><h1>Media</h1></summary>
<p>

image

</p>
</details>

---

# Changelog

:cl:
- add: Added Python, Pollock, Webley, K38, Fitz, Wood Furniture Viper, Energy Pistol, PDW-9, and Svalinn to security loadouts as new Duty Weapon options.
- tweak: Modified the descriptions of all handguns obtained via Security Officer Loadouts to explicitly state that they actually belong to the security officer. Apparently people were being stupid and confiscating weapons from their own Secoffs that they were entirely intended to have.

### CODE REVIEW

**Comment by DangerRevolution** [comment]
Instead of le entity bloat; At minimum, a system should be considered that lets loadout entries override names / descriptions instead of shitting out 40 new weapons so Security can use them.

**Comment by VMSolidus** [comment]
> Instead of le entity bloat; At minimum, a system should be considered that lets loadout entries override names / descriptions instead of shitting out 40 new weapons so Security can use them.

That's literally what parenting is for.

**Comment by DangerRevolution** [comment]
> > Instead of le entity bloat; At minimum, a system should be considered that lets loadout entries override names / descriptions instead of shitting out 40 new weapons so Security can use them.
> 
> That's literally what parenting is for.

Instead of a system that allows for a modified name / description on a gun; we've now added 15 new entities with 40 components on each entity just to change the name and description.

**Comment by bruhmogus** [comment]
no no no god please no do not make DEATH SQUAD and MORE SYNDICATE weapons sec gear :sob:

**Comment by VMSolidus** [comment]
> no no no god please no do not make DEATH SQUAD and MORE SYNDICATE weapons sec gear 😭

No. Referring to completely generic items as being "SYNDICATE" is both cringe and NRP.

**Comment by bruhmogus** [comment]
> > no no no god please no do not make DEATH SQUAD and MORE SYNDICATE weapons sec gear 😭
> 
> No. Referring to completely generic items as being "SYNDICATE" is both cringe and NRP.

the problem is wizden compared to this because 90% of the secoff guns are "kill this guy" material and get people shot on inspecting the person

**Comment by VMSolidus** [comment]
> > > no no no god please no do not make DEATH SQUAD and MORE SYNDICATE weapons sec gear 😭
> > 
> > 
> > No. Referring to completely generic items as being "SYNDICATE" is both cringe and NRP.
> 
> the problem is wizden compared to this because 90% of the secoff guns are "kill this guy" material and get people shot on inspecting the person

We aren't wizden, we don't care what Wizden does, we aren't interested in following Wizden's design decisions, what Wizden does has zero factor in what we're doing.

**Comment by DEATHB4DEFEAT** [comment]
> Instead of le entity bloat; At minimum, a system should be considered that lets loadout entries override names / descriptions instead of shitting out 40 new weapons so Security can use them.

Adding new entities is fine for now, I have plans for user-set names and descriptions soon.
*Loadouts* can override their name/description *in the character editor* already though.

**Comment by VMSolidus** [comment]
> > Instead of le entity bloat; At minimum, a system should be considered that lets loadout entries override names / descriptions instead of shitting out 40 new weapons so Security can use them.
> 
> Adding new entities is fine for now, I have plans for user-set names and descriptions soon. _Loadouts_ can override their name/description _in the character editor_ already though.

This *does* demonstrate that there is a use-case for loadouts overriding the name/description of the item to be spawned, but that is also still waaaaay outside of the scope of this PR, and is an unreasonable thing to ask here.

**Comment by bruhmogus** [comment]
> > > > no no no god please no do not make DEATH SQUAD and MORE SYNDICATE weapons sec gear 😭
> > > 
> > > 
> > > No. Referring to completely generic items as being "SYNDICATE" is both cringe and NRP.
> > 
> > 
> > the problem is wizden compared to this because 90% of the secoff guns are "kill this guy" material and get people shot on inspecting the person
> 
> We aren't wizden, we don't care what Wizden does, we aren't interested in following Wizden's design decisions, what Wizden does has zero factor in what we're doing.

you missed my point completely. not everyone SOLELY plays specifically ee servers, mostly they play wizden, and having what would normally be "nobody should ever have this" weapons as 90% of the secoff weapons would absolutely fuck over not only traitor detection but also confuse everyone new to ee but not the Basic Bitch™ branch, it'd get too many people shot over "oh shit that was just jerry's gun and not a syndicate agent, whoops"

**Comment by VMSolidus** [comment]
> > > > > no no no god please no do not make DEATH SQUAD and MORE SYNDICATE weapons sec gear 😭
> > > > 
> > > > 
> > > > No. Referring to completely generic items as being "SYNDICATE" is both cringe and NRP.
> > > 
> > > 
> > > the problem is wizden compared to this because 90% of the secoff guns are "kill this guy" material and get people shot on inspecting the person
> > 
> > 
> > We aren't wizden, we don't care what Wizden does, we aren't interested in following Wizden's design decisions, what Wizden does has zero factor in what we're doing.
> 
> you missed my point completely. not everyone SOLELY plays specifically ee servers, mostly they play wizden, and having what would normally be "nobody should ever have this" weapons as 90% of the secoff weapons would absolutely fuck over not only traitor detection but also confuse everyone new to ee but not the Basic Bitch™ branch, it'd get too many people shot over "oh shit that was just jerry's gun and not a syndicate agent, whoops"

Literally the only people who can get these guns are Security Officers. If you see *absolutely anyone other than Security* carrying a gun, you are 100% safe to treat them as a threat. If you open fire on a Secoff for carrying a handgun, you are 100% in the wrong. I'd also like to point out that the Mk58 handgun, the "Default vanilla security gun" is available in traitor uplinks.

**Comment by bruhmogus** [comment]
> > > > > > no no no god please no do not make DEATH SQUAD and MORE SYNDICATE weapons sec gear 😭
> > > > > 
> > > > > 
> > > > > No. Referring to completely generic items as being "SYNDICATE" is both cringe and NRP.
> > > > 
> > > > 
> > > > the problem is wizden compared to this because 90% of the secoff guns are "kill this guy" material and get people shot on inspecting the person
> > > 
> > > 
> > > We aren't wizden, we don't care what Wizden does, we aren't interested in following Wizden's design decisions, what Wizden does has zero factor in what we're doing.
> > 
> > 
> > you missed my point completely. not everyone SOLELY plays specifically ee servers, mostly they play wizden, and having what would normally be "nobody should ever have this" weapons as 90% of the secoff weapons would absolutely fuck over not only traitor detection but also confuse everyone new to ee but not the Basic Bitch™ branch, it'd get too many people shot over "oh shit that was just jerry's gun and not a syndicate agent, whoops"
> 
> Literally the only people who can get these guns are Security Officers. If you see _absolutely anyone other than Security_ carrying a gun, you are 100% safe to treat them as a threat. If you open fire on a Secoff for carrying a handgun, you are 100% in the wrong. I'd also like to point out that the Mk58 handgun, the "Default vanilla security gun" is available in traitor uplinks.

the issue with that line of thinking is that its easy to round remove someone BEFORE realising their gun was just security instead of syndicate

**Comment by Eagle-0** [comment]
> > > > > > > no no no god please no do not make DEATH SQUAD and MORE SYNDICATE weapons sec gear 😭
> > > > > > 
> > > > > > 
> > > > > > No. Referring to completely generic items as being "SYNDICATE" is both cringe and NRP.
> > > > > 
> > > > > 
> > > > > the problem is wizden compared to this because 90% of the secoff guns are "kill this guy" material and get people shot on inspecting the person
> > > > 
> > > > 
> > > > We aren't wizden, we don't care what Wizden does, we aren't interested in following Wizden's design decisions, what Wizden does has zero factor in what we're doing.
> > > 
> > > 
> > > you missed my point completely. not everyone SOLELY plays specifically ee servers, mostly they play wizden, and having what would normally be "nobody should ever have this" weapons as 90% of the secoff weapons would absolutely fuck over not only traitor detection but also confuse everyone new to ee but not the Basic Bitch™ branch, it'd get too many people shot over "oh shit that was just jerry's gun and not a syndicate agent, whoops"
> > 
> > 
> > Literally the only people who can get these guns are Security Officers. If you see _absolutely anyone other than Security_ carrying a gun, you are 100% safe to treat them as a threat. If you open fire on a Secoff for carrying a handgun, you are 100% in the wrong. I'd also like to point out that the Mk58 handgun, the "Default vanilla security gun" is available in traitor uplinks.
> 
> the issue with that line of thinking is that its easy to round remove someone BEFORE realising their gun was just security instead of syndicate

Then take a second and look at the gun before shooting them? This is is a player issue, not a loadout issue lmao.

**Comment by bruhmogus** [comment]
> > > > > > > > no no no god please no do not make DEATH SQUAD and MORE SYNDICATE weapons sec gear 😭
> > > > > > > 
> > > > > > > 
> > > > > > > No. Referring to completely generic items as being "SYNDICATE" is both cringe and NRP.
> > > > > > 
> > > > > > 
> > > > > > the problem is wizden compared to this because 90% of the secoff guns are "kill this guy" material and get people shot on inspecting the person
> > > > > 
> > > > > 
> > > > > We aren't wizden, we don't care what Wizden does, we aren't interested in following Wizden's design decisions, what Wizden does has zero factor in what we're doing.
> > > > 
> > > > 
> > > > you missed my point completely. not everyone SOLELY plays specifically ee servers, mostly they play wizden, and having what would normally be "nobody should ever have this" weapons as 90% of the secoff weapons would absolutely fuck over not only traitor detection but also confuse everyone new to ee but not the Basic Bitch™ branch, it'd get too many people shot over "oh shit that was just jerry's gun and not a syndicate agent, whoops"
> > > 
> > > 
> > > Literally the only people who can get these guns are Security Officers. If you see _absolutely anyone other than Security_ carrying a gun, you are 100% safe to treat them as a threat. If you open fire on a Secoff for carrying a handgun, you are 100% in the wrong. I'd also like to point out that the Mk58 handgun, the "Default vanilla security gun" is available in traitor uplinks.
> > 
> > 
> > the issue with that line of thinking is that its easy to round remove someone BEFORE realising their gun was just security instead of syndicate
> 
> Then take a second and look at the gun before shooting them? This is is a player issue, not a loadout issue lmao.

"look at the gun before shooting them"
my brother in space christ you'd have to run directly towards them, open their strip menu, then inspect the item thats in their hand before figuring out if its syndicate or sec
also you are overestimating how smart the average secoff is

**Comment by VMSolidus** [comment]
> > > > > > > no no no god please no do not make DEATH SQUAD and MORE SYNDICATE weapons sec gear 😭
> > > > > > 
> > > > > > 
> > > > > > No. Referring to completely generic items as being "SYNDICATE" is both cringe and NRP.
> > > > > 
> > > > > 
> > > > > the problem is wizden compared to this because 90% of the secoff guns are "kill this guy" material and get people shot on inspecting the person
> > > > 
> > > > 
> > > > We aren't wizden, we don't care what Wizden does, we aren't interested in following Wizden's design decisions, what Wizden does has zero factor in what we're doing.
> > > 
> > > 
> > > you missed my point completely. not everyone SOLELY plays specifically ee servers, mostly they play wizden, and having what would normally be "nobody should ever have this" weapons as 90% of the secoff weapons would absolutely fuck over not only traitor detection but also confuse everyone new to ee but not the Basic Bitch™ branch, it'd get too many people shot over "oh shit that was just jerry's gun and not a syndicate agent, whoops"
> > 
> > 
> > Literally the only people who can get these guns are Security Officers. If you see _absolutely anyone other than Security_ carrying a gun, you are 100% safe to treat them as a threat. If you open fire on a Secoff for carrying a handgun, you are 100% in the wrong. I'd also like to point out that the Mk58 handgun, the "Default vanilla security gun" is available in traitor uplinks.
> 
> the issue with that line of thinking is that its easy to round remove someone BEFORE realising their gun was just security instead of syndicate

First of all why are you round-removing antags on MRP servers? When the standard of behavior on MRP servers is not to be going around round removing people? Do you have any idea how many people I've banned from DS14 because they were round removing people who had a pack of cigarettes? Or security officers gibbing people once they've been arrested?

**Comment by bruhmogus** [comment]
> > > > > > > > no no no god please no do not make DEATH SQUAD and MORE SYNDICATE weapons sec gear 😭
> > > > > > > 
> > > > > > > 
> > > > > > > No. Referring to completely generic items as being "SYNDICATE" is both cringe and NRP.
> > > > > > 
> > > > > > 
> > > > > > the problem is wizden compared to this because 90% of the secoff guns are "kill this guy" material and get people shot on inspecting the person
> > > > > 
> > > > > 
> > > > > We aren't wizden, we don't care what Wizden does, we aren't interested in following Wizden's design decisions, what Wizden does has zero factor in what we're doing.
> > > > 
> > > > 
> > > > you missed my point completely. not everyone SOLELY plays specifically ee servers, mostly they play wizden, and having what would normally be "nobody should ever have this" weapons as 90% of the secoff weapons would absolutely fuck over not only traitor detection but also confuse everyone new to ee but not the Basic Bitch™ branch, it'd get too many people shot over "oh shit that was just jerry's gun and not a syndicate agent, whoops"
> > > 
> > > 
> > > Literally the only people who can get these guns are Security Officers. If you see _absolutely anyone other than Security_ carrying a gun, you are 100% safe to treat them as a threat. If you open fire on a Secoff for carrying a handgun, you are 100% in the wrong. I'd also like to point out that the Mk58 handgun, the "Default vanilla security gun" is available in traitor uplinks.
> > 
> > 
> > the issue with that line of thinking is that its easy to round remove someone BEFORE realising their gun was just security instead of syndicate
> 
> First of all why are you round-removing antags on MRP servers? When the standard of behavior on MRP servers is not to be going around round removing people? Do you have any idea how many people I've banned from DS14 because they were round removing people who had a pack of cigarettes? Or security officers gibbing people once they've been arrested?

i'm not, but you also imply that EVERY SINGLE EE BASED SERVER runs off of mrp

**Comment by VMSolidus** [comment]
> > > > > > > > > no no no god please no do not make DEATH SQUAD and MORE SYNDICATE weapons sec gear 😭
> > > > > > > > 
> > > > > > > > 
> > > > > > > > No. Referring to completely generic items as being "SYNDICATE" is both cringe and NRP.
> > > > > > > 
> > > > > > > 
> > > > > > > the problem is wizden compared to this because 90% of the secoff guns are "kill this guy" material and get people shot on inspecting the person
> > > > > > 
> > > > > > 
> > > > > > We aren't wizden, we don't care what Wizden does, we aren't interested in following Wizden's design decisions, what Wizden does has zero factor in what we're doing.
> > > > > 
> > > > > 
> > > > > you missed my point completely. not everyone SOLELY plays specifically ee servers, mostly they play wizden, and having what would normally be "nobody should ever have this" weapons as 90% of the secoff weapons would absolutely fuck over not only traitor detection but also confuse everyone new to ee but not the Basic Bitch™ branch, it'd get too many people shot over "oh shit that was just jerry's gun and not a syndicate agent, whoops"
> > > > 
> > > > 
> > > > Literally the only people who can get these guns are Security Officers. If you see _absolutely anyone other than Security_ carrying a gun, you are 100% safe to treat them as a threat. If you open fire on a Secoff for carrying a handgun, you are 100% in the wrong. I'd also like to point out that the Mk58 handgun, the "Default vanilla security gun" is available in traitor uplinks.
> > > 
> > > 
> > > the issue with that line of thinking is that its easy to round remove someone BEFORE realising their gun was just security instead of syndicate
> > 
> > 
> > First of all why are you round-removing antags on MRP servers? When the standard of behavior on MRP servers is not to be going around round removing people? Do you have any idea how many people I've banned from DS14 because they were round removing people who had a pack of cigarettes? Or security officers gibbing people once they've been arrested?
> 
> i'm not, but you also imply that EVERY SINGLE EE BASED SERVER runs off of mrp

We outright have it in our fork design document that we don't cater to NRP or LRP servers. That's Wizden's territory.

**Comment by Eagle-0** [comment]
Once again we face the issue of asking people to roleplay in a roleplay game. Truely it's over for spessgame.

**Comment by VMSolidus** [comment]
Literally not even a problem. It's an entirely binary decision tree of:
>See person wearing extremely obvious Security Uniform = "Oh they must be Security. It's their job to be armed."
>See person who isn't wearing an extremely obvious Security Uniform and waving around a gun, regardless of what gun that is = "Oh they aren't Security, they shouldn't be armed. I should run away from them or else they might shoot me"

**Comment by Mnemotechnician** [comment]
> if only all of the brainpower and passion on this whole discussion thread went over to bugfixes and core systems instead 🙏

Amen.

**Comment by VMSolidus** [comment]
Summon the maintainers and approve it to end the annoying discussion lmao.

**Comment by bruhmogus** [comment]
> Literally not even a problem. It's an entirely binary decision tree of:
> 
> * See person wearing extremely obvious Security Uniform = "Oh they must be Security. It's their job to be armed."
> * See person who isn't wearing an extremely obvious Security Uniform and waving around a gun, regardless of what gun that is = "Oh they aren't Security, they shouldn't be armed. I should run away from them or else they might shoot me"

once again you completely missed what im trying to say, if they ARE security with the gun, sure, fine, but if they AREN'T sec has to do the job of "shoot them to be safe but waste meds and possibly get yelled at by everyone OR try to stun them and risk dying" in a span of three seconds

**Comment by DEATHB4DEFEAT** [comment]
> Summon the maintainers and approve it to end the annoying discussion lmao.

I have an idea

**Comment by Remuchi** [comment]
> i'm not, but you also imply that EVERY SINGLE EE BASED SERVER runs off of mrp

The solution to your problem was invented a few decades ago.
It's called REVERSE COMMIT.

I, however, want to raise another point of concern here.
I do not care about the guns being syndicate or Deathsquad or ert or whatever
What I do care about is the guns balancing. For instance, lets take the Python. 6 rounds cylinder revolver with 2.0 firerate. Seems legit, yeah? Until we take a look at the Inspector, an issued to detective revolver. It has the same 6 rounds cylinder while having 1.5 fire rate.

It was fine before since weapons being in uplink should be generally better than regular ones by design. But with this approach it all goes to the waste.

The PR looks fine otherwise. Expect the bloat but it was raised before already.

**Review by Peptide90 — APPROVED** [review]

**Review by OldDanceJacket — APPROVED** [review]

**Pull request merged**
