### PR TITLE
CI/CD Fix Attempt 3

### PR DESCRIPTION
**Pull request by VMSolidus**
Last one didn't work, tests were still dead in the water. So now we'll have to try running them on 8.0.204 instead of 100.

### CODE REVIEW

**Review by DangerRevolution — APPROVED** [review]
Guh

**Comment by VMSolidus** [comment]
image

**SCREAMS**

**Comment by VMSolidus** [comment]
image
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by VMSolidus** [comment]
image

After 4 hours, I have finally whittled down the list to a single error, and have thoroughly learned everything I need to know to maintain systems with the new engine changes. The only thing left to do is merge: https://github.com/Simple-Station/Einstein-Engines/pull/312

Then I can finally get this show on the road.

**Comment by VMSolidus** [comment]
Made pointless by #423

**Pull request closed without merging**
