### PR TITLE
The Blood Cult

### PR DESCRIPTION
**Pull request by Remuchi**
# Description
Adds a new game mode - The Blood Cult. 
Hail to Nar'Sie!

---

# TODO

- [x] Gamemode
- [x] Roles
- [x] Runes
- [x] Constructs
- [x] Structures
  - [x] Forge
  - [x] Archives
  - [x] Altar
  - [x] Pylon
    - [x] Structure
    - [x] Placement System
  - [x] Airlocks
    - [x] Repulsor system
  - [x] Construction system
- [x] Items
  - [x] Eldritch Whetstone
  - [x] Construct Shell
  - [x] Mirror Shield
  - [x] True Nar'sian Hardened Armor
  - [x] Flagellant's Robe
  - [x] Eldritch Longsword
  - [x] Zealot's Blindfold
    - [ ] Night vision system
  - [x] Shuttle Curse
  - [x] Veil Shifter
  - [x] Void Torch
 - [x] Reagents
   - [x] Holy Water
- [ ] Actions
  - [x] Cult Magic
    - [x] Stun
    - [x] Teleport
    - [x] Electromagnetic Pulse
    - [x] Shadow Shackles
    - [x] Twisted Construction
    - [x] Summon Combat Equipment
    - [x] Summon Ritual Dagger
    - [x] Blood Rites
  - [ ] Cult Leader Magic
    - [ ] Final Reckoning
    - [ ] Mark Target
    - [ ] Eldritch Pulse
  - [ ] Construct's Magic 
    - [ ] Artificer 
      - [ ] Summon Cult Floor 
      - [ ] Summon Cult Wall
      - [ ] Greater Conjuration
      - [ ] Summon Soulstone
    - [ ] Wraith 
      - [ ] Phase Shift
    - [ ] Juggernaut
      - [ ] Shield
      - [ ] Gauntlet Echo
- [x] Cult leader selection system
- [ ] Rending/Apocalypse rune placement markers
EXTRA:
- [ ] Spirit Realm rune
- [x] Eldritch language
- [ ] Conceal magic
- [ ] Ru locale
---

<details><summary><h1>Media</h1></summary>
<p>

Example Media Embed

</p>
</details>

---

# Changelog

:cl:
- add: Added Blood Cult Gamemode.

### CODE REVIEW

**Comment by whateverusername0** [comment]
Can you believe it guys? Mah'weyh pleggh at e'ntrath! Just a week away!

**Comment by Remuchi** [comment]
Technically It's still work in progress but it's now ready for review.

**Review by VMSolidus — APPROVED** [review]
Excellent work Remuchi.

**Comment by Erisfiregamer1** [comment]
am I about to live witness Cult being merged

**Comment by gluesniffler** [comment]
> am I about to live witness Cult being merged

given the extent of the work we probably should have @DEATHB4DEFEAT or @Pspritechologist also review it

**Review by Peptide90 — APPROVED** [review]

**Comment by Erisfiregamer1** [comment]
> > am I about to live witness Cult being merged
> 
> given the extent of the work we probably should have @DEATHB4DEFEAT or @Pspritechologist also review it

nawwwwwww it's funnier to speedmerge things and fix the thousand bugs later

**Pull request merged**
