### PR TITLE
Mirror: recolor detective stamp

### PR DESCRIPTION
**Pull request by SimpleStation14**
###### `d3d9898d2acd7cbc14ca74835ba172497ff91efe`

PR opened by <a href="https://github.com/TheShuEd"> TheShuEd</a> at 2024-03-09 13:57:56 UTC
PR merged by <a href="https://github.com/web-flow"> web-flow</a> at 2024-03-11 01:57:20 UTC

---

PR changed 2 files with 1 additions and 1 deletions.

The PR had the following labels:
- No C#
- Changes: Sprites

---

<details open="true"><summary><h1>Original Body</h1></summary>

> ## About the PR
> recolor detective's rubber stamp to brown
> Sprited by Awlod
> 
> ## Why / Balance
> too similar in color to the seals of the sec
> (dec is not sec!)
> 
> ## Media
> image
> 
> - [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 

</details>

### CODE REVIEW

**Review by DangerRevolution — COMMENTED** [review]
this should be checked for what colour this is

**Review by VMSolidus — APPROVED** [review]
Yea, this is fine.

**Comment by stellar-novas** [comment]
The detective is sec again, are we doing this?

**Comment by DangerRevolution** [comment]
Detective is still in Sec in Delta, and even Wizden reverted the Detective --> Service change (apparently) so I don't see the need in this.

**Pull request closed without merging**
