### PR TITLE
Mirror: new book - Tales of a Tired Janitor

### PR DESCRIPTION
**Pull request by SimpleStation14**
###### `0a6921d5ef90ebaaf1e054178f2889889eea661c`

PR opened by <a href="https://github.com/Boaz1111"> Boaz1111</a> at 2024-01-23 09:28:08 UTC

---

PR changed 2 files with 22 additions and 0 deletions.

The PR had the following labels:
- No C#

---

<details open="true"><summary><h1>Original Body</h1></summary>

> 
> 
> 
> ## About the PR
> 
> I added a new book, as requested by someone in the discord. This book is about the life of a janitor working aboard a (presumably NT) space station "14". They describe the things they have to deal with, the disrespect from others, the lack of good equipment.
> ## Why / Balance
> 
> More variety in books, especially books indirectly talking about life on a space station, and the jobs on said station.
> ## Technical details
> 
> 
> ## Media
> 
> 
> - [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> ## Breaking changes
> 
> 
> **Changelog**
> 
> 
> 
> no cl 

</details>

### CODE REVIEW

**Review by DangerRevolution — APPROVED** [review]

**Review by DangerRevolution — CHANGES_REQUESTED** [review]
sounds like something that should be a note in a damp closet :shrug:

**Review by VMSolidus — APPROVED** [review]
It's pretty mediocre, but unfortunately required for the DV merges. Ree

**Review by DangerRevolution — APPROVED** [review]

**Comment by VMSolidus** [comment]
Wait nevermind I can just yeet any mention of mediocre books from the other PR lmao.

**Comment by DangerRevolution** [comment]
> It's pretty mediocre, but unfortunately required for the DV merges. Ree

convincing argument, set to automer-

**Comment by VMSolidus** [comment]
Yea one of these days I shall 1984 the entire list of godawful 4chan books.

**Pull request merged**
