### PR TITLE
Make Debris Actually Dangerous

### PR DESCRIPTION
**Pull request by VMSolidus**
# Description

Meant to be a counterpart to this PR: https://github.com/Simple-Station/Einstein-Engines/pull/342

This makes it so that glass shards and floor tiles will embed in people when colliding with them, dealing a small amount of damage. This is also helpful for both making Monstermos with Physics Based Air Throws both less dangerous, and more interesting. Now if an explosion turns a room into a whirlwind of scrap metal, people will actually be significantly concerned about trying not to get hit by debris. 

# Changelog

:cl:
- add: Glass/Crystal shards and floor tiles now deal damage and embed in victims when colliding with them.

### CODE REVIEW

**Comment by DEATHB4DEFEAT** [comment]
https://titlecaseconverter.com

**Comment by VMSolidus** [comment]
> https://titlecaseconverter.com

That would be a hilarious thing to make a bot to automate, sending this to Solidus every time he doesn't title case

**Comment by VMSolidus** [comment]
This also prevents floor tiles from just killing EVERYONE in a room, to be fair. Monstermos turns spaced rooms into a very brief blender when combined with Physics Based Air Throws, enough that if a Nukie spaces a room, they better stand aside and wait a brief moment for the shrapnel to fly past. But killing everyone with spammed hits isn't intended

**Review by DangerRevolution — APPROVED** [review]
seems interesting, worth getting feedback on how this'll work out

**Review by DEATHB4DEFEAT — APPROVED** [review]

**Pull request merged**
