### PR TITLE
Expand N.E.I.L.

### PR DESCRIPTION
**Pull request by VMSolidus**
# Description

N.E.I.L. has been expanded. You are welcome.

# Changelog

:cl:
- add: N.E.I.L. now has announcement sounds for every announcement

### CODE REVIEW

**Comment by DEATHB4DEFEAT** [comment]
> N.E.I.L. has been expanded. You are welcome.

Is he now NNN.EEE.III.LLL...?

**Review by DEATHB4DEFEAT — CHANGES_REQUESTED** [review]
These sound terrible

**Comment by VMSolidus** [comment]
> These sound terrible

Find someone who knows how to edit audio then. Lol.

**Comment by VMSolidus** [comment]
It seems like we basically need someone who knows how to clean up the audio, and then add the audio effects that were present in the original announcements.

**Comment by DEATHB4DEFEAT** [comment]
> It seems like we basically need someone who knows how to clean up the audio, and then add the audio effects that were present in the original announcements.

Ask Rane :trollface:

**Comment by DEATHB4DEFEAT** [comment]
Closing due to inactivity, reopen if you get a better sample.

**Pull request closed without merging**
