### PR TITLE
Fix Pride and Courier Vendors Not Being Able To Say Thank You, and Crashing the Game Out of Protest

### PR DESCRIPTION
**Pull request by VMSolidus**
# Description

This fixes a crash related to the CourierDrobe and PrideVend not having thank you messages. Instead of deleting the ability to say a thank you message, I have elected to add thank you messages to both vendors.

# Media

image

### CODE REVIEW

**Comment by DEATHB4DEFEAT** [comment]
Nice title

**Comment by VMSolidus** [comment]
image
Better lol?

**Comment by DEATHB4DEFEAT** [comment]
> image Better lol?

Yeah but not Title Case

**Review by DEATHB4DEFEAT — APPROVED** [review]

**Review by DangerRevolution — APPROVED** [review]
be gay, do crime

**Pull request merged**
