### PR TITLE
Make Stamres Show in Actual Damage Resistance View

### PR DESCRIPTION
**Pull request by whateverusername0**
# Description
title

using the same branch for everything makes me happy.

image

no cl no fun

### CODE REVIEW

**Comment by VMSolidus** [comment]
PR'ing from a several week old fork moment.

**Comment by whateverusername0** [comment]
whuh what

**Comment by VMSolidus** [comment]
> whuh what

You have merge conflicts on a file that hasn't existed for a few weeks. :)
Content.Server/Nyanotrasen/Psionics/PsionicsSystem.cs doesn't live there anymore lol.

**Comment by whateverusername0** [comment]
> > whuh what
> 
> You have merge conflicts on a file that hasn't existed for a few weeks. :) Content.Server/Nyanotrasen/Psionics/PsionicsSystem.cs doesn't live there anymore lol.

lol

**Comment by DEATHB4DEFEAT** [comment]
curse of the force push

**Pull request closed without merging**
