### PR TITLE
Social Anxiety Trait Renamed

### PR DESCRIPTION
**Pull request by CilliePaint**
# Description

Changes the Social Anxiety Traits Name, Description, and ID's

---

# Changelog

:mefinks:
- tweak: Changed the name of the Social Anxiety Trait.

### CODE REVIEW

**Review by DEATHB4DEFEAT — APPROVED** [review]

**Comment by DangerRevolution** [comment]
But... why?

**Comment by DEATHB4DEFEAT** [comment]
> But... why?

It's not accurate

**Comment by FoxxoTrystan** [comment]
Semm gud

**Review by VMSolidus — APPROVED** [review]
Yes this is fine. More accurate to what the trait actually does. 
Real "Social Anxiety" would be tied to a hypothetical morale point system.

**Pull request merged**
