### PR TITLE
Meson Scanner Goggles

### PR DESCRIPTION
**Pull request by WarMechanic**
# Description

Engineering buff, and SS13 feature now in SS14.
Engineering Goggles, now 'Meson Scanner Goggles' get an active toggle that lets them visualise the station's structure through walls.

I basically did no work on this, and haven't done any PR work for like half a year so I'm very rusty. So I would like to see this reviewed first.

---

# TODO

- [x] resurrect abandoned wizden pr
- [x] attach media (im watching poe2 streams)
- [ ] change `MesonsNonviewable` component? or look for a better alternative that might be more maintainer friendly
- [ ] stop halving my fps when i turn on mesons
- [ ] make sure its good quality

---

<details><summary><h1>Media</h1></summary>
<p>

image

</p>
</details>

---

# Changelog

:cl: notquitehadouken, WarMechanic
- tweak: Meson Scanner Goggles (previously Engineering Goggles) can now see through walls.

### CODE REVIEW

**Comment by WarMechanic** [comment]
depending on how the code works, i want to change from using `MesonsNonviewable` component to use the tag system instead? something like that

having to blacklist certain things seems pretty shit for maintainers

**Comment by WarMechanic** [comment]
oh yeah also turning on the meson goggles halves my fps for some reason, i need to investigate that too

**Comment by WarMechanic** [comment]
need to remove enable/disable visibility out of a frametime loop, and simply update whats visible when things are appended/dropped from a list

**Comment by FoxxoTrystan** [comment]
I think best is to add a whitelist, not a blacklist.

**Comment by WarMechanic** [comment]
> I think best is to add a whitelist, not a blacklist.

yeah i thought so too, but if i make a whitelist ill have to hide everything not in the whitelist (which requires checks)
so here a blacklist might be technically preferable but ill need to ensure its not annoying for maintainers
would inheriting components from base mobs / items / whatever be fine?

**Comment by WarMechanic** [comment]
i dont like mesons when they disable visibility of certain things you already see, and i dont know enough about shaders to have only walls/tiles appear in the place of darkness / los (this visualisation of mesons would be ideal)

i might revisit this in the future, but im going to be occupied with poe2 launch so gg

**Comment by FoxxoTrystan** [comment]
> > I think best is to add a whitelist, not a blacklist.
> 
> yeah i thought so too, but if i make a whitelist ill have to hide everything not in the whitelist (which requires checks) so here a blacklist might be technically preferable but ill need to ensure its not annoying for maintainers would inheriting components from base mobs / items / whatever be fine?

Il prefer instead we use like CM14 uses for xeno to see resin, instead of hiding, we use the normal FOV, and just render things that we want to see, including walls, pehaps floors, ect...

**Pull request closed without merging**
