### PR TITLE
Fix Shuttle FTL

### LINKED ISSUE #410: Shuttle FTL Jump Fails to Reach Expedition Planets Due to Beacon Issue
# Description

Greetings everyone,

I have encountered an issue where expeditions are not functioning correctly in the current build. Specifically, when selecting FTL in the shuttle control console and attempting to jump to an expedition planet, nothing happens. 

Upon investigation, I found that if you disable the `BeaconsOnly` in the `FTLDestinationComponent` on the planet, the shuttle can jump, but it lands in various distant locations from the actual dungeon. This suggests that the problem is related to the Beacon.

# Reproduction

1. Open the shuttle control console.
2. Select FTL.
3. Attempt to jump to an expedition planet.
4. Observe that nothing happens.

# Expected behavior

1. Open the shuttle control console.
2. Select FTL.
3. Attempt to jump to an expedition planet.
4. The shuttle should successfully jump to the designated expedition planet and land near the dungeon.

# Media

https://github.com/Simple-Station/Einstein-Engines/assets/163446847/a97f8c12-7749-4f3d-947b-11b2625c5c87

# Additional context

- Disabling `BeaconsOnly` allows the jump but causes the shuttle to land at incorrect locations.
- The issue appears to be related to the Beacon functionality in the `FTLDestinationComponent`.
- I'm currently debugging to understand and fix the issue. Any insights or suggestions on what might be causing this problem would be greatly appreciated.

### PR DESCRIPTION
**Pull request by VMSolidus**
# Description

The bot failed to cherry pick this, resulting in us having had broken shuttle FTL this whole time. 
This PR cherrypicks https://github.com/space-wizards/space-station-14/pull/26305

Fixes #410

### CODE REVIEW

**Review by DangerRevolution — APPROVED** [review]
Weird that an April Fools PR made it into Wiz master

**Comment by VMSolidus** [comment]
Lol, yea I grabbed that too, and was busy searching for any other relevant PRs for a good few minutes before I looked back and realized it was an April Fools PR, then reverted it.

**Comment by v0idRift** [comment]
https://github.com/Simple-Station/Einstein-Engines/issues/410

**Comment by DangerRevolution** [comment]
> #410

Thanks for the reminder :)

**Review by Peptide90 — APPROVED** [review]

**Pull request merged**
