### PR TITLE
ERT Overhaul 3.0

### PR DESCRIPTION
**Pull request by Tryded**
## About the PR

Make ERT balanced and give options for admins to choose from. Also mostly gives energy based guns to ERT and less powerful weaponry for anyone that isn't security ERT.

Requires https://github.com/Simple-Station/Einstein-Engines/pull/42

## Why / Balance

ERT has been seen as pinatas by most people and admins as their gear is extremely overpowered compared to everyone else  causing the members to just fight without resistance.
## Technical details

YAML only
## Media

TO DO:

## - [ ] New Equipment:
 - [ ] IK-30
 - [ ] Hardsuits
 - [ ] Immolator Cannon
 - [ ] Misc
## - [ ] Ghost Roles/Starter Kits
 - [x] Leader
 - [x] ERT Members

### CODE REVIEW

**Comment by Tryded** [comment]
New Plan: Just make it so the commander can buy certain amount of bundles which are made for each ERT member so that admins have less stuff to micro manage

**Comment by Tryded** [comment]
On pause until Modsuits are added

**Comment by Peptide90** [comment]
1 month since last update, is this still on hold / being worked on?

**Comment by DangerRevolution** [comment]
Emma mentioned to me that they've left this, going to close :)

**Pull request closed without merging**
