### PR TITLE
Mirror: Increase lone ops TC from 40 to 60

### PR DESCRIPTION
**Pull request by SimpleStation14**
###### `75287db55545e0bd32425721e5d3751f2913de39`

PR opened by <a href="https://github.com/Plykiya"> Plykiya</a> at 2024-03-15 06:28:37 UTC

---

PR changed 3 files with 34 additions and 1 deletions.

The PR had the following labels:
- No C#
- Status: Needs Review

---

<details open="true"><summary><h1>Original Body</h1></summary>

> 
> 
> 
> ## About the PR
> 
> Created a new lone ops outfit load out that just gives them a 60 TC radio.
> 
> ## Why / Balance
> 
> I've never seen a lone ops succeed... they're kind of pathetic of a threat when compared to a space dragon or a ninja. I was also recommended to do it by an admin.... maybe as a shitpost suggestion?
> 
> ## Technical details
> 
> Created new 60TC uplink in the yml, created new lone ops loadout in the yml that uses the 60TC uplink. Functionally the same as the base nukie 40TC loadout besides the difference in TC.
> 
> ## Media
> 
> 
> - [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> image
> 
> ## Breaking changes
> 
> 
> **Changelog**
> 
> 
> 
> :cl:
> - tweak: Lone operatives now start with 60TC instead of 40TC.

</details>

### CODE REVIEW

**Review by DangerRevolution — APPROVED** [review]
why not :shrug:

**Comment by VMSolidus** [comment]
I'm going to close this because this is actually a pretty good example of an NRP-oriented balance change that we don't want. Remember how many times people have complained that the Loneop exists solely to kill 20 people and make the shuttle get called? Now imagine that this lets them buy a juggsuit, grenadier vest, and a china lake. Now they can kill 30 people and get the shuttle called to end the round. 

Also I'd love to give a shoutout to the fact that they gave them a free 3rd syndie hardsuit too.

**Comment by DangerRevolution** [comment]
> I'm going to close this because this is actually a pretty good example of an NRP-oriented balance change that we don't want. Remember how many times people have complained that the Loneop exists solely to kill 20 people and make the shuttle get called? Now imagine that this lets them buy a juggsuit, grenadier vest, and a china lake. Now they can kill 30 people and get the shuttle called to end the round.
> 
> Also I'd love to give a shoutout to the fact that they gave them a free 3rd syndie hardsuit too.

with all these mirror PR's i'm accepting some in case they're needed in any of the other mirrors, and then we can just change this after & forks will change this anyways

**Comment by VMSolidus** [comment]
> > I'm going to close this because this is actually a pretty good example of an NRP-oriented balance change that we don't want. Remember how many times people have complained that the Loneop exists solely to kill 20 people and make the shuttle get called? Now imagine that this lets them buy a juggsuit, grenadier vest, and a china lake. Now they can kill 30 people and get the shuttle called to end the round.
> > Also I'd love to give a shoutout to the fact that they gave them a free 3rd syndie hardsuit too.
> 
> with all these mirror PR's i'm accepting some in case they're needed in any of the other mirrors, and then we can just change this after & forks will change this anyways

Yea that's totally fine actually. If you state in your review of things that that you think the code is fine but the balance may be questionable, that'll work great.

**Pull request closed without merging**
