### PR TITLE
Add Europa Map to Rotation

### PR DESCRIPTION
**Pull request by Ichaie**
# Description

This PR adds an old map to rotation called "Europa", originally a planetary map, but due to several problems it was not able to be played, I updated a good part of the map adding things necessary to be able to be played in the EE code, using the same idea To make the Glacier map a "planet", I created a parallax using the desert texture for the map and set the atmosphere on the outer side to a temperature of 356.2 K (83 C) with a high presence of CO2

---

# TODO

- [x] Rework eng
   - [x] add Super Matter engine
   - [x] better layout

- [x] Rework Epi
  - [x] Better layout
  - [x] missing content

- [x] Minor fixes on the map

- [x] test the map
- [x] add image 

---

<details><summary><h1>Media</h1></summary>
<p>

Europa-0

</p>
</details>

---

# Changelog

:cl:
- add: added a new map called "Europa" to rotation

### CODE REVIEW

**Review by FoxxoTrystan — CHANGES_REQUESTED** [review]
Test fails valid

**Comment by Ichaie** [comment]
errors fixed

**Comment by Ichaie** [comment]
Europa-0

**Comment by VMSolidus** [comment]
> Europa-0

Huh, this is actually my first time ever seeing this map by the way. It has a lot of problems I can see.

**Comment by Ichaie** [comment]
> > Europa-0
> 
> Huh, this is actually my first time ever seeing this map by the way. It has a lot of problems I can see.

Yes, it has several problems, it would probably be better to do a complete rework

**Comment by VMSolidus** [comment]
> > > Europa-0
> > 
> > 
> > Huh, this is actually my first time ever seeing this map by the way. It has a lot of problems I can see.
> 
> Yes, it has several problems, it would probably be better to do a complete rework

If you want, I can help work on some of the issues. For one I'd like to put a Supermatter engine in it. Epi also needs some stuff that it's missing, like Oracle and Sophia.

Security's Permabrig is missing prisoner latejoin cryo.
image

**Comment by VMSolidus** [comment]
image

Another thing, the HoS's WT550 needs to be removed, since they get it from their loadouts now,.

**Comment by Ichaie** [comment]
> > > > Europa-0
> > > 
> > > 
> > > Huh, this is actually my first time ever seeing this map by the way. It has a lot of problems I can see.
> > 
> > 
> > Yes, it has several problems, it would probably be better to do a complete rework
> 
> If you want, I can help work on some of the issues. For one I'd like to put a Supermatter engine in it. Epi also needs some stuff that it's missing, like Oracle and Sophia.
> 
> Security's Permabrig is missing prisoner latejoin cryo. image

I'm going to update the TODO in PR and start reworking these parts, I don't think you need to worry about helping

**Comment by Ichaie** [comment]
Europa-0

**Comment by Ichaie** [comment]
Europa-0

**Review by VMSolidus — APPROVED** [review]

**Review by Remuchi — APPROVED** [review]
looks cool

**Pull request merged**
