### PR TITLE
Admin Tooling Cherry Picks

### PR DESCRIPTION
**Pull request by sleepyyapril**
# Description

Link to every PR I cherry-picked:
1. https://github.com/new-frontiers-14/frontier-station-14/pull/2283
2. https://github.com/space-wizards/space-station-14/pull/29219
3. https://github.com/space-wizards/space-station-14/pull/30075
4. https://github.com/space-wizards/space-station-14/pull/28639
5. https://github.com/space-wizards/space-station-14/pull/32527
6. https://github.com/space-wizards/space-station-14/pull/28030
7. https://github.com/space-wizards/space-station-14/pull/28178

The main purpose of this PR is the first cherry-picked PR. It adds the ability for admins to reply to ahelps via discord using an HTTP POST request. See all relevant details in the initial PR by Myzumi.

### CODE REVIEW

**Comment by sleepyyapril** [comment]
Test fails unrelated

**Comment by sleepyyapril** [comment]
UPDATE: The bot side is ready, so long as you are using a RedBot instance. Cog is located [here](https://github.com/sleepyyapril/april-cogs)

**Review by VMSolidus — APPROVED** [review]
Test fails are indeed unrelated.

**Comment by sleepyyapril** [comment]
Code review required for latest PR, made custom changes to allow for discord role being used as a title, discord color being used as color, and allowing you to change the admin bwoink name color.

**Review by OldDanceJacket — APPROVED** [review]

**Pull request merged**
