### PR TITLE
Pistol-Whipping (Guns as Melee Weapons)

### PR DESCRIPTION
**Pull request by angelofallars**
# Description

Adds the ability to use guns as melee weapons and throwing weapons. 

The gun melee attack is a Light Attack done with a right click. The attack rate is slower than average melee weapons.

The cooldown on melee attacks after shooting has been removed entirely, so you can right-click immediately after shooting (like in hero shooters 😎). The cooldown on shooting after a melee attack has been set to a constant 0.5 seconds.

## Balance

Technically speaking, weaving shooting and pistol-whipping lowers your overall DPS in most cases, because you can't shoot for 0.5 seconds after doing a melee attack. With _skillful_ usage, however, it provides some key tactical advantages:
- Preserving ammo by dealing damage without firing a shot.
- Deal stamina damage as a natural effect of dealing melee Blunt damage.
  - Most non-pistol guns have increased blunt stamina damage factors to help with this.
- Bypassing Piercing resists of armors with a higher Piercing resist than Blunt resist like plate carriers.
- Doing the combo of right-clicking immediately after shooting deals a big burst of damage.

Pistol-whipping also helps as a last resort when you run out of ammo. However, it's almost always better to use a proper melee weapon instead of a gun as a pure melee weapon, because you can't power attack with guns and the guns' melee attack rate are slower by design than most melee weapons.

Shotguns benefit the most from pistol-whipping, because their ideal range is close-range where a melee attack can be performed, and their low fire rate means they're not affected too much by the 0.5s shooting cooldown.

Guns have received throwing damage. You can throw guns at the enemy once you're out of ammo to deal extra damage. I think this makes fights a little more spectacular to watch.

Melee damage sorted by group (from least to greatest):

1. Revolver
2. Pistol (+ Energy Pistol)
3. Sniper rifle
4. Rifle  (+ Energy Rifle)
5. Sub Machine Gun
6. Shotgun
7. Light Machine Gun (L6 saw)
8. Heavy Machine Gun

## Media

**mk 58**

image

**Kardashev-Mosin (Wielded)**

 image

**Basic Combat**

https://github.com/user-attachments/assets/922998d1-0cd0-4fea-8f0b-365bcff3c12b

**Particle Decelerator Combo (80 damage)**

https://github.com/user-attachments/assets/ce62334a-13dd-46d9-9c0e-453e26bf1261

Combo: Shoot + Power Attack, wait 1.6s then Power Attack + Throw

This combo costs 90 stamina which almost depletes 100 stamina leaving you vulnerable, so the Vigor trait can help you pull off this combo. 

## Changelog

:cl: Skubman
- add: Pistol-whipping has been added. You can press right click with a gun to perform a Light Attack. Most guns will deal Blunt damage, apart from the Kardashev-Mosin dealing Piercing/Slash damage with its bayonet. Weaving bullets and melee attacks correctly will give you the upper hand in combat.
- add: Guns can now be thrown to deal the same damage as their melee damage.

### CODE REVIEW

**Review by VMSolidus — APPROVED** [review]
Woah.

**Review by sleepyyapril — APPROVED** [review]

**Comment by VMSolidus** [comment]
image

Oh hey, a test fail I've never seen before!

**Comment by angelofallars** [comment]
> image
> 
> Oh hey, a test fail I've never seen before!

Fixed [08b0647](https://github.com/Simple-Station/Einstein-Engines/pull/1335/commits/08b0647fa5d3965e79442ff20ec66db79e0c6de3)

**Comment by VMSolidus** [comment]
**IVAN, WORRY NOT, WHEN OUT OF BOOLET, USE MOSIN AS JAVELIN**

**Pull request merged**
