### PR TITLE
Event Rebalance

### PR DESCRIPTION
**Pull request by Mnemotechnician**
# Description
Significant event rebalance based on my own experience and feedback from some players, mostly aimed to improve low-pop experience and prevent multiple instances of same event occurring at once.

Added weaker versions of hostile critter events. Those versions spawn 2-3 times less critters and come with a different announcement: SlimesSpawnWeak, SpidersSpawnWeak, XenoVentsWeak.

Rebalanced the following events:
- AnomalySpawn - reoccurrence delay of 8 minutes to prevent multiple anomalies from spawning with a delay of a few seconds (which has happened many times).
- BluespaceArtifact - same, but 5 minutes.
- BluespaceLocker - 15 minute reoccurrence delay and no more than 4 occurrences per shift because it's really annoying.
- BreakerFlip, BureaucraticError, ClericalError - reoccurrence delay of 5 minutes.
- GasLeak - reoccurrence delay of 7 minutes.
- KudzuGrowth - reoccurrence delay of 10 minutes.
- MeteorSwarm - reoccurrence delay of 5 minutes, reduced player count requirement from 10 to 7.
- MouseMigration, VentCritters (mice) - reoccurrence delay of 3 minutes, reduced playercount requirement from 35 to 0. (Those two events are identical but have different announcements, might as well remove one of them)
- CockroachMigration - reoccurrence delay of 15 minutes.
- PowerGridCheck - reoccurrence delay of 2 minutes (same as the maximum duration of the event).
- SolarFlare, VentClog - reoccurrence delay of 5 minutes.
- SlimesSpawn, SpiderSpawn - reoccurrence delay of 12 minutes.
- MimicVendorRule - reoccurrence delay of 5 minutes.
- XenoVents - increased weight from 1 to 6.
- MothroachSpawn - decreased player requirement from 15 to 1.
- MundaneDischarge - reoccurrence delay of 15 minutes.
- NoosphericZap - increased the weight from 12 to 25 and added a reoccurrence delay of 15 minutes. (Making it more likely to occur on regular intervals rather than randomly throughout the shift).
- NoosphericFry - changed the glimmer range to 550-1000Ψ.
- PsionicCatGotYourTongue - changed the glimmer range to 590-1000Ψ.
- MassMindSwap - **MADE TEMPORARY** and increased glimmer burn range to 350-450Ψ.
- FreeProber - changed the glimmer range to 550-1000Ψ.
- GlimmerRandomSentience - reoccurence delay of 15 minutes, minimum of 10 player, and a glimmer range of 500-900Ψ.
- GlimmerRevenantSpawn - glimmer range of 700-900Ψ. (There's already another revenant spawn event that isn't based on glimmer, wtf?)

Rebalanced the following midround antags:
- DragonSpawn - doubled the weight, from 1 to 2.
- NinjaSpawn - reduced the player requirement from 40 to 20 (loneop had 20, and is far more destructive than a ninja). Also reduced reoccurrence delay to 45 minutes.
- ZombieOutbreak - earliest start moved from 90 minutes to 60, weight reduced from 2.5 to 2, number of initial infected cut down from 3 to 2.
- LoneOpsSpawn - reduced the player requirement from 20 to 15 and increased the reoccurrence delay from 30 to 45 minutes.
- 

Re-added the following events:
- ClosetSkeleton, with a minimum of 15 players and reoccurence delay of 25 minutes.
- RandomSentience - with a reoccurence delay of 10 minutes and a maximum of 3 occurences.

<details><summary><h1>Media</h1></summary>
<p>

New events:

image

image

</p>
</details>

---

# Changelog
:cl:
- tweak: Most station events were rebalanced to better suit low-pop rounds.
- add: Weakened versions of vent critter events can now occur on low-pop rounds.
- tweak: After a lot of complaints, the mass mindswap event is no longer permanent.

### CODE REVIEW

**Comment by Mnemotechnician** [comment]
Uh, MassMindswapRule never even supported the isTemporary rule - it still traps you in the new body. I guess it will stay permanent until someone rewrites that nyano system.

**Comment by VMSolidus** [comment]
> Uh, MassMindswapRule never even supported the isTemporary rule - it still traps you in the new body. I guess it will stay permanent until someone rewrites that nyano system.

This is one of the *many* bugs I had to fix in my Refactor.

**Comment by Mnemotechnician** [comment]
> > Uh, MassMindswapRule never even supported the isTemporary rule - it still traps you in the new body. I guess it will stay permanent until someone rewrites that nyano system.
> 
> This is one of the _many_ bugs I had to fix in my Refactor.

So it's fixed in all servers that have it early-merged? That's neat.

**Comment by VMSolidus** [comment]
I just now realized you balanced the glimmer events around the fact that literally every single one of our downstreams has early merged the psionic refactor lmao.

**Review by VMSolidus — APPROVED** [review]

**Review by OldDanceJacket — APPROVED** [review]

**Pull request merged**
