### PR TITLE
Port Parkstation Audio Library

### PR DESCRIPTION
**Pull request by VMSolidus**
# Description

By request from @DEATHB4DEFEAT , this ports https://github.com/Simple-Station/Parkstation/pull/55

:cl: VMSolidus
- add: Many new sound effects have been implemented for items.

### CODE REVIEW

**Review by DangerRevolution — COMMENTED** [review]
I assume this changes sounds as needed? Also; Shadowkin sounds? Are we porting those?

**Comment by VMSolidus** [comment]
> I assume this changes sounds as needed? Also; Shadowkin sounds? Are we porting those?

Yes, we are. :)

**Comment by DEATHB4DEFEAT** [comment]
> > I assume this changes sounds as needed? Also; Shadowkin sounds? Are we porting those?
> 
> Yes, we are. :)

What for?

**Comment by VMSolidus** [comment]
> > > I assume this changes sounds as needed? Also; Shadowkin sounds? Are we porting those?
> > 
> > 
> > Yes, we are. :)
> 
> What for?

Audio library objects can be re-used and modified to suit other purposes, so of all the assets to store upstream, they're one of the most sensible. Even if Shadowkin aren't upstreamed to EE, having the audio files here still makes sense. Plus it was just part of the original PR that I cherrypicked here.

**Review by DangerRevolution — APPROVED** [review]

**Comment by DEATHB4DEFEAT** [comment]
While playing, I noticed the cup pickup sound is *very loud*. #474 :)
I don't remember any other issues, might properly review this later but doesn't matter.

**Review by OldDanceJacket — APPROVED** [review]

**Pull request merged**
