### PR TITLE
Glorious Canisters

### PR DESCRIPTION
**Pull request by FoxxoTrystan**
# Description

Changed the Canisters Sprites to a better updated one, no more ugly 2D Flat Canisters!
Also update the TG Sprite from Tank Canisters now shiny!

---

<details><summary><h1>Media</h1></summary>
<p>

image
image

</p>
</details>

---

# Changelog

:cl:
- tweak: Resprited gas canisters
- tweak: Resprited gas tanks

### CODE REVIEW

**Review by VMSolidus — APPROVED** [review]
Actually good sprites, on my Repo? Woah!

**Comment by DEATHB4DEFEAT** [comment]
The gas tank sprites look way too bright (oversaturated?), canisters look great though.

Also read the PR template next time, you left a ton of unnecessary stuff it asked you to remove.

**Comment by VMSolidus** [comment]
> The gas tank sprites look way too bright (oversaturated?), canisters look great though.
> 
> Also read the PR template next time, you left a ton of unnecessary stuff it asked you to remove.

Oh, yea I see what you mean. If Trystan will let me, I can go over the sprites with weathering effects and make them fit better.

**Comment by FoxxoTrystan** [comment]
> > The gas tank sprites look way too bright (oversaturated?), canisters look great though.
> > Also read the PR template next time, you left a ton of unnecessary stuff it asked you to remove.
> 
> Oh, yea I see what you mean. If Trystan will let me, I can go over the sprites with weathering effects and make them fit better.

Go on and proceed!

**Comment by DangerRevolution** [comment]
This should be drafted if VM is editing these.

**Review by DangerRevolution — APPROVED** [review]
looks alright, i approve, re-requested new VM review

**Comment by VMSolidus** [comment]
I have finished editing the tanks after a long hiatus

**Pull request merged**
