### PR TITLE
Thieves Outside of Traitor

### PR DESCRIPTION
**Pull request by ShatteredSwords**
# Description

Mirroring a PR from Floof that I was much too lazy to cherry-pick. This just changes gamemodes outside of tator and rev to allow thieves if it makes sense to.

---

# Changelog

:cl:
- tweak: Thieves are now in Survival, Hellshift, and Extended.

### CODE REVIEW

**Comment by Mnemotechnician** [comment]
test fail is fake

**Review by DangerRevolution — CHANGES_REQUESTED** [review]
Give credit

**Comment by Mnemotechnician** [comment]
> Give credit

no

**Comment by ShatteredSwords** [comment]
> Give credit

Okay
https://github.com/Fansana/floofstation1/pull/153
Hey look, I made it!

**Review by DangerRevolution — APPROVED** [review]

**Review by VMSolidus — APPROVED** [review]

**Review by OldDanceJacket — APPROVED** [review]

**Pull request merged**
