### PR TITLE
Feat: Port Delta-V Glimmer Wisps

### PR DESCRIPTION
**Pull request by Mnemotechnician**
# Description
Ports https://github.com/DeltaV-Station/Delta-v/pull/1383 with all due changes.

Also moves some files from delta-v/nyano namespaces to the root namespace.

# TODO
- [X] Port fun
- [X] Test fun
- [X] Record fun

<details><summary><h1>Media</h1></summary>
<p>

I had to compress the shit out of this video, so it's about as good as it can get.

https://github.com/user-attachments/assets/3ab9d328-ae6e-4a6c-8a48-9da22783579a

</p>
</details>

---

# Changelog
:cl:
- add: Raising glimmer too high can now cause glimmer wisps to start haunting the station.

### CODE REVIEW

**Comment by Mnemotechnician** [comment]
Bonus point is that psionic NPCs will now automatically use their noospheric zap power on targeted entities:

https://github.com/user-attachments/assets/1253249d-9c08-4e87-b4d9-f9b192c6d708

**Comment by bruhmogus** [comment]
> Bonus point is that psionic NPCs will now automatically use their noospheric zap power on targeted entities:
> 
>  transcoded.shit.mp4

will this make the oracle start indiscriminately gunning down crew

**Review by FoxxoTrystan — APPROVED** [review]
We would need to move Glimmer Spider here too.

**Comment by Mnemotechnician** [comment]
> will this make the oracle start indiscriminately gunning down crew

Soon™, oracle hostile HTN

**Review by VMSolidus — APPROVED** [review]
It's time for Wispy Nonsense.

**Pull request merged**
