### PR TITLE
#481 , #362 , #25893 , Issue Fixes 

### LINKED ISSUE #481: Fork specific options are still called "Delta-V" in the settings
# Media

image

### PR DESCRIPTION
**Pull request by Tmanzxd**
Rename Fork Specific Options From "DeltaV" To "EinsteinEngines", Fixes #481

### CODE REVIEW

**Comment by Tmanzxd** [comment]
this fixes #25893

**Comment by angelofallars** [comment]
I suggest splitting the PR into three separate PRs, each addressing #481, #362 and #25893 as these are three unrelated issues.

**Comment by Tmanzxd** [comment]
> I suggest splitting the PR into three separate PRs, each addressing #481, #362 and #25893 as these are three unrelated issues.

Working on that now, I'll close this PR then do 3 separate ones to make it cleaner

**Comment by Tmanzxd** [comment]
3 Separate Pull Requests are here now:
https://github.com/Simple-Station/Einstein-Engines/pull/630
https://github.com/Simple-Station/Einstein-Engines/pull/631
https://github.com/Simple-Station/Einstein-Engines/pull/632

**Pull request closed without merging**
