### PR TITLE
Revert "Random Announcer System (#415)"

### PR DESCRIPTION
**Pull request by VMSolidus**
# Description

This needed a little more time to cook, apparently it wasn't setting an announcer at all in the first place, and genuinely was just picking random sounds from random announcers.

### CODE REVIEW

**Comment by DEATHB4DEFEAT** [comment]
I'd rather a fix than revert, what exactly is the problem?

**Comment by VMSolidus** [comment]
> I'd rather a fix than revert, what exactly is the problem?

The problem seems to be(at least from observation) that announcements are not correctly using Fallbacks, and are instead quite literally playing a random announcement from any announcer. The announcer could be Neil, and PirateRadioSpawnRule triggers(which does not, and should never have an announcement), which bafflingly sets off Michael's Code Blue alert. Or seemingly any announcement.

**Comment by DEATHB4DEFEAT** [comment]
> > I'd rather a fix than revert, what exactly is the problem?
> 
> The problem seems to be(at least from observation) that announcements are not correctly using Fallbacks, and are instead quite literally playing a random announcement from any announcer. The announcer could be Neil, and PirateRadioSpawnRule triggers(which does not, and should never have an announcement), which bafflingly sets off Michael's Code Blue alert. Or seemingly any announcement.

Weird, no idea how that happened, I'll look into it.

**Comment by VMSolidus** [comment]
> > > I'd rather a fix than revert, what exactly is the problem?
> > 
> > 
> > The problem seems to be(at least from observation) that announcements are not correctly using Fallbacks, and are instead quite literally playing a random announcement from any announcer. The announcer could be Neil, and PirateRadioSpawnRule triggers(which does not, and should never have an announcement), which bafflingly sets off Michael's Code Blue alert. Or seemingly any announcement.
> 
> Weird, no idea how that happened, I'll look into it.

I appreciate it

**Comment by DEATHB4DEFEAT** [comment]
I'm not having any issues on master, is this a problem with DS?

image

**Comment by VMSolidus** [comment]
> I'm not having any issues on master, is this a problem with DS?
> 
> image

It was originally reported by DS, but then I was able to reproduce it locally on an EE Master.

**Comment by DEATHB4DEFEAT** [comment]
> > I'm not having any issues on master, is this a problem with DS?
> > [image](https://private-user-images.githubusercontent.com/77995199/349370681-9b459c9f-b82a-426e-bd0e-013ba04e0979.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTQyNDgsIm5iZiI6MTcyMTE5Mzk0OCwicGF0aCI6Ii83Nzk5NTE5OS8zNDkzNzA2ODEtOWI0NTljOWYtYjgyYS00MjZlLWJkMGUtMDEzYmEwNGUwOTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA1MjU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYzAxMWU5NDFlY2NmZGYzNmY1NDBkYjliZmEyNDQ0MzE3Y2UzMjQ4NTYzYmFlMDY0ZjZkZTA4MTMxYjIzZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KrlkzvdJVXuvqH6UhlsXtxCZzCgcG9XnVUiKya3c6BI)
> 
> It was originally reported by DS, but then I was able to reproduce it locally on an EE Master.

Could you record the issue?

**Comment by DEATHB4DEFEAT** [comment]
Closing this in favor of https://github.com/Simple-Station/Einstein-Engines/pull/557.
Tell me if this should be reopened.

**Pull request closed without merging**
