### PR TITLE
Revert Salvage Shittle and Trading Post removal

### PR DESCRIPTION
**Pull request by VMSolidus**
It's been gone for a bit too long.

### CODE REVIEW

**Comment by DangerRevolution** [comment]
not sure this is a good idea, forks should be able to edit this to their preference :O

**Comment by stellar-novas** [comment]
Make it a cvar :godo:

**Review by Peptide90 — APPROVED** [review]

**Review by DangerRevolution — APPROVED** [review]
i personally don't like this but it *is* a functional PR, this should be checked that it causes no fuckery with changed bounties from Delta

**Comment by VMSolidus** [comment]
> Congratulations, I wanted to see if this'd get merged without a proper test, and it did.
> 
> This will cause unintended and potentially game-breaking issues if left alone, as the trade station spawning is already handeled within the [CargoSystem](https://github.com/Simple-Station/Einstein-Engines/blob/9d7cc5f3678b7c4e54a6cad164fbd29c07cb39e4/Content.Server/Cargo/Systems/CargoSystem.Shuttle.cs#L389-L435), assuming the [GridFill](https://github.com/Simple-Station/Einstein-Engines/blob/9d7cc5f3678b7c4e54a6cad164fbd29c07cb39e4/Content.Shared/CCVar/CCVars.cs#L1407-L1411) cvar isn't [disabled](https://github.com/Simple-Station/Einstein-Engines/blob/9d7cc5f3678b7c4e54a6cad164fbd29c07cb39e4/Content.Server/Cargo/Systems/CargoSystem.Shuttle.cs#L372-L373), as would be the case in non-release builds.

I had already told my maintainers to stop merging things without anyone doing tests.

**Comment by VMSolidus** [comment]
> Sure thing, next time you introduce a bug I'll just stay quiet

Everything still works, there's just two trade stations now. I'll go fix that.

**Pull request merged**
