### PR TITLE
Catch-Up Cherry Pick 2

### PR DESCRIPTION
**Pull request by DEATHB4DEFEAT**
# Description

Picked 400 commits (and skipped many, many more) from WizDen since #540.
Stopped at commit 332f54a3aebe669f6e50d26e7b047f0bdc28e0fb (Lobby Refactor).

---

# TODO

- [x] Pick
- [x] Compile
- [x] Fix runtime errors
- [ ] Fix up humanoid profile editor
- [ ] Test everything

---

# Changelog

:cl:
- add: Merged 400 WizDen PRs. Happy testing!

### CODE REVIEW

**Comment by DEATHB4DEFEAT** [comment]
noo! merge conflicts! my worst enemy

**Review by VMSolidus — APPROVED** [review]
It finally runs.

**Review by FoxxoTrystan — APPROVED** [review]

**Comment by VMSolidus** [comment]
image

This was the only bug I could find that wasn't pre-existing.

**Comment by VMSolidus** [comment]
Fuck it let's go.

**Pull request merged**
