### PR TITLE
Directional Animated Vendors

### PR DESCRIPTION
**Pull request by VMSolidus**
# Description

This PR adds in new sprites for vending machines, imported from Baystation12. These sprites are notably different from /tg/station sprites in that they include directional facings, and aren't just mono direction. This allows mappers to have more variety in how they can arrange rooms. But more importantly, it's also something that is desperately wanted by #395 so that hostile vending machines actually face people that they're trying to attack. 

ShareX_YQkAjaj4s8

### CODE REVIEW

**Comment by DangerRevolution** [comment]
image
Does this include the soundfile for the vendor?

**Comment by VMSolidus** [comment]
> image Does this include the soundfile for the vendor?

This doesn't! Ooh that sounds like fun.

**Comment by VMSolidus** [comment]
Setting this to DO NOT MERGE until I have finished fixing the shader states on the sprites. They look stupidly crisp and shiny in that image because they all had bad shader states causing them to just totally ignore all lighting, rather than have glow effects on only the glowing portions. Here's an example of what they should actually generally look like when I have finished fixing their shaders.

https://github.com/Simple-Station/Einstein-Engines/assets/16548818/fb6ae0f7-c5e9-4962-89f0-ec92147b266e

**Comment by FoxxoTrystan** [comment]
Why is there a bunch of random sprite of drinks and food?
Is this related to the PR at all?

(Checked files in github i hope its not this fucking it up)

**Comment by VMSolidus** [comment]
> Why is there a bunch of random sprite of drinks and food? Is this related to the PR at all?
> 
> (Checked files in github i hope its not this fucking it up)

Yea the original PR I cherrypicked this from included them by request from ODJ, who had intended to use them to add new items to vendors. They're the entirety of the roster of food related items from Baystation12. Some of them are actually used by the new vending machines included in this PR.

**Comment by FoxxoTrystan** [comment]
> > Why is there a bunch of random sprite of drinks and food? Is this related to the PR at all?
> > (Checked files in github i hope its not this fucking it up)
> 
> Yea the original PR I cherrypicked this from included them by request from ODJ, who had intended to use them to add new items to vendors. They're the entirety of the roster of food related items from Baystation12. Some of them are actually used by the new vending machines included in this PR.

Quick question then, is this PR ready for Review?

**Comment by VMSolidus** [comment]
> > > Why is there a bunch of random sprite of drinks and food? Is this related to the PR at all?
> > > (Checked files in github i hope its not this fucking it up)
> > 
> > 
> > Yea the original PR I cherrypicked this from included them by request from ODJ, who had intended to use them to add new items to vendors. They're the entirety of the roster of food related items from Baystation12. Some of them are actually used by the new vending machines included in this PR.
> 
> Quick question then, is this PR ready for Review?

No, not really. I need to finish polishing stuff with it first.

**Comment by Peptide90** [comment]
> Why is there a bunch of random sprite of drinks and food? Is this related to the PR at all?
> 
> (Checked files in github i hope its not this fucking it up)

The ODJ requests were fitness stuff and barber stuff which has been on my list forever. The fitness stuff has animations and stuff too but not implemented. Needs to be on use.

All the food sprites iirc have entities as I implemented all them for myself to make the vendors complete e.g. solsnacks/ mars vend / kawaii vend thing nipon tan. 

There’s however lots of unused sprites for the smart fridges etc which were 32x64 as well as all the storage visuals for a lot of the fridges, intend to do them at a later date.

**Comment by DEATHB4DEFEAT** [comment]
I was about to review this on the web but holy shit

image

I'll review this tomorrow maybe in VSCode so it doen't lag eternally and so I can mass "view" pngs.

**Comment by DEATHB4DEFEAT** [comment]
Damn, I was going to add the `Holy Shit` label but DR beat me to it.

**Review by DangerRevolution — CHANGES_REQUESTED** [review]
is every vendor resprited here? Donut vend, boardgame vend & solaris coffee vend seems to be the same.

**Comment by VMSolidus** [comment]
> is every vendor resprited here? Donut vend, boardgame vend & solaris coffee vend seems to be the same.

No. And why did you request changes for this question? I don't have the ability to make said resprites for the vendors that don't have resprites.

**Comment by VMSolidus** [comment]
image

FUCK, ALRIGHT. I'M YEETING THAT STUPID PROTOTYPE DURING MY NEXT CODE SESSION.

**Comment by DangerRevolution** [comment]
> > is every vendor resprited here? Donut vend, boardgame vend & solaris coffee vend seems to be the same.
> 
> No. And why did you request changes for this question? I don't have the ability to make said resprites for the vendors that don't have resprites.

draw them :)

**Comment by VMSolidus** [comment]
> > > is every vendor resprited here? Donut vend, boardgame vend & solaris coffee vend seems to be the same.
> > 
> > 
> > No. And why did you request changes for this question? I don't have the ability to make said resprites for the vendors that don't have resprites.
> 
> draw them :)

No. I'll just close this PR and we get nothing. Please don't require me to make sprites. I'm not that kind of artist.

**Review by DangerRevolution — APPROVED** [review]
This needs an issue opened with all the unsprited vendors

**Review by Peptide90 — APPROVED** [review]
Approving because anything additional to this can be a different PR. It's been merged for months on DS since I added them so lets get it merged proper.

**Pull request merged**
