### PR TITLE
Languages Markers

### PR DESCRIPTION
**Pull request by FoxxoTrystan**
# Description

Require #459 

Add 3 optional settings for LanguagePrototypes to play with richtext tags to they could be reconized as Makings

color - Set a specefic color to the text.
fontId - Set a font to the text by using the Id.
fontSize - Set the size of the text

All 3 are optional if not set message will be handeled like normal.

This should be mostly used to know what language your currently speaking and assist with markings.
Take note those changes happent only in the TextBox chat, bubblechat is left unchanged.

---

# TODO

- [x] Add Markings
- [x] Add Fonts

---

<details><summary><h1>Media</h1></summary>
<p>

image
image

</p>
</details>

---

# Changelog

:cl: FoxxoTrystan
- add: Languages are now marked in the chat!

### CODE REVIEW

**Comment by PuroSlavKing** [comment]
Will there be language icons in the language selection menu, chat and in the text cloud? 🥺

**Comment by DangerRevolution** [comment]
> Will there be language icons in the language selection menu, chat and in the text cloud? 🥺

Not the author of the PR; but from what I've spoke to them:

1. Menu can support icons
2. Chat menu cannot support icons
3. Chat cloud cannot support icons

2 and 3 would need very big changes to how the Chat Menu and Chat Cloud are formatted.

**Comment by FoxxoTrystan** [comment]
> > Will there be language icons in the language selection menu, chat and in the text cloud? 🥺
> 
> Not the author of the PR; but from what I've spoke to them:
> 
> 1. Menu can support icons
> 2. Chat menu cannot support icons
> 3. Chat cloud cannot support icons
> 
> 2 and 3 would need very big changes to how the Chat Menu and Chat Cloud are formatted.

They could but you would need to change compleatly the UI of both ends and by god... im not going to try to touch ANCIENT UI.

**Review by DEATHB4DEFEAT — APPROVED** [review]
I haven't looked at this in-game, but the code is fine.

**Review by DangerRevolution — APPROVED** [review]
Font is a little Sus but yaml is changeable if people don't like it

**Pull request merged**
