### PR TITLE
Adds PKA & Jetpack Module for Salvage Cyborgs

### PR DESCRIPTION
**Pull request by gluesniffler**
# Description

Gives salvage borgs a special jetpack module with half of the capacity of a normal mini-jetpack. Granting them about 2 minutes of thrust, which allows them to be more useful in space, partake in some rescue missions and to some extent be independent for a limited amount of time if something happens to the salvagers.

It also adds a PKA module, which gives them a PKA which can't be wielded, leading to a hilarious accuracy penalty.

---

<details><summary><h1>Media</h1></summary>
<p>

Demo of the Modules
[Crafting demo, basic usage](https://youtu.be/k6xbEAtudVA "PKA/Jetpack Borg Demo")

Stormtrooper aim vs dragon AI
[Soloing space dragon AI, ft. stormtrooper aim](https://www.youtube.com/watch?v=0e8iXbtD-Pc "Stormtrooper vs Space Dragon AI")

Refillable jetpack module demo
[Refilling jetpack](https://youtu.be/y7Ie81NV2QM "Refill showcase of the jetpack module")
</p>
</details>

---

# Changelog

:cl:
- add: Added an unlockable PKA and Jetpack module to Salvage Cyborgs

### CODE REVIEW

**Review by DangerRevolution — APPROVED** [review]
How do you refill the jetpack?

**Comment by gluesniffler** [comment]
> How do you refill the jetpack?

image

> Special, **non-refillable** jetpack module. 

Reasoning for this is mostly balancing, refilling the module would require help from someone with hands anyway, and since jetpacks inherit from tanks, they don't seem to have any gas whitelisting, so I cannot prevent players from just stuffing it with liquid oxygen to make 'em last a ridiculous amount of time.

The point is to just give borgs a lil' bit more independence and not make them bricks you have to drag around at all times (the current state), thus you might as well just send the borgs off to Epi periodically if they want refills. Happy to adjust values for crafting cost/thrust duration with this in mind.

**Comment by VMSolidus** [comment]
> > How do you refill the jetpack?
> 
> image
> 
> > Special, **non-refillable** jetpack module.
> 
> Reasoning for this is mostly balancing, refilling the module would require help from someone with hands anyway, and since jetpacks inherit from tanks, they don't seem to have any gas whitelisting, so I cannot prevent players from just stuffing it with liquid oxygen to make 'em last a ridiculous amount of time.
> 
> The point is to just give salv borgs a lil' bit more independence and not make them bricks you have to drag around at all times (the current state), thus you might as well just send the borgs off to Epi periodically if they want refills. Happy to adjust values for crafting cost/thrust duration with this in mind.

Reasoning behind this is somewhat faulty. There's no such thing as Liquid Oxygen, it's just an oxygen canister that contains double the volume of oxygen, but cannot itself be refilled to that volume, and cannot overpressure people's air tanks. It really should just be renamed to "Double-capacity Oxygen Canister".

**Comment by gluesniffler** [comment]
> Reasoning behind this is somewhat faulty. There's no such thing as Liquid Oxygen, it's just an oxygen canister that contains double the volume of oxygen, but cannot itself be refilled to that volume, and cannot overpressure people's air tanks.
<details><summary><h2>Liquid Oxygen Is Different.</h2></summary>
<p>
For any readers who come in later, Liquid Oxygen is not just double the volume of oxygen, but is also chilled to a very low temperature, which leads to being able to fit more mols in a container as per Boyle's Law as seen in the image below, in jetpack calculations, this extends flight duration. In the case of this particular jetpack's capacity, thrust time would go from 2 minutes to about 6:30 minutes.

Gas comparisons

</p>
</details> 

<h2> Constraints </h2>

If it's not a balance concern, I'm all for letting brogs get their jetpacks refilled, but after doing some digging on the system itself, there's also constraints in how their modules handle items, particularly:

**1.** The items are only instantiated when in a Borg's possession, and they cannot drop their items.
**2.** There's seemingly no way to fetch the ID of the provided item even after creation if its not in the borg.
**3.** Borgs can only use whats *inside* of the module, so giving the module itself a Jetpack attribute is not good enough.

<h2> Options to Improve (from easiest to hardest)</h2>

**1.** Just change the thrust duration to either match a Mini Jetpack (4min), or the duration on liquid oxy (6:30min).
**2.** Either change the module (by making the jetpack lingering/stackable lol) or the cyborg itself to instead use a whitelisted slot. This would require the salvagers to either take one from EVA, or sacrifice a jetpack of their own. Which I feel isn't too convenient compared to simply crafting it.
**3.** Make a new jetpack + system that would allow them to eject the canister, or refill their stuff when clicking on a gas canister, akin to a welder torch with fuel... which overall feels overkill.

My gut says Occam's Razor is better here, and just making the module itself last a lot longer would be better than having to code an entirely new system for a single module, **but I'd appreciate input here!!!**

**Comment by gluesniffler** [comment]
Added a refillable feature to the modules, in summary it checks for the prototypes of items to be created on module insertion, and if its a "JetpackMicroFilled" it will add the EntityUid to a BorgJetpackComponent. This is then used to check on the GasCanisterSystem.cs whenever something is inserted, refilled or displayed in the UI to make sure jetpack modules work like a jetpack would.

Couldn't get a way to make it so that the contents would be initialized on item creation, the methods currently require an existing borg chassis to do so.

**Review by VMSolidus — APPROVED** [review]

**Pull request merged**
