### PR TITLE
Phoron Will Make Us Rich

### PR DESCRIPTION
**Pull request by VMSolidus**
# Phoron Will Make Us Rich
Phoron Will Make Us Rich

# Changelog

:cl: VMSolidus
- add: Phoron Will Make Us Rich

### CODE REVIEW

**Comment by toasterpm87** [comment]
Phoron will make us rich.

**Comment by LovelyLophi** [comment]
John Nanotransen didn't kill his brother John Nanustrasen for this.

**Review by DangerRevolution — APPROVED** [review]
do we want to change the material too? like plasma glass etc

**Comment by FoxxoTrystan** [comment]
Ehh is this PR still going?
And i do like Plasma more then Phoron name personnaly.

How would server handle this? CVar?

**Comment by DangerRevolution** [comment]
this needs conflicts fixed & we need to get to a consensus about this

**Comment by VMSolidus** [comment]
I'll revisit this later with a less shitposty PR

**Pull request closed without merging**
