### PR TITLE
Hotfix Linter

### PR DESCRIPTION
**Pull request by VMSolidus**
# Description

SOMEHOW THIS GOT PAST THE LINTER. THE FUCK?

### CODE REVIEW

**Review by DEATHB4DEFEAT — APPROVED** [review]
:trollface:

**Comment by Evgencheg** [comment]
:trollface:

**Comment by Eagle-0** [comment]
:trollface:

**Comment by gluesniffler** [comment]
:trollface:

**Comment by Mnemotechnician** [comment]
Huh??

**Comment by stellar-novas** [comment]
:trollface:

**Review by Peptide90 — APPROVED** [review]

**Pull request merged**
