### PR TITLE
The Floors! (Resprites)

### PR DESCRIPTION
**Pull request by FoxxoTrystan**
# Description

Edit/Resprite most of the floors in-game because in all honest TG Floors... currently... are extremly flat and old... even TG already has upgraded their floors...
This also changed some minor edits to decals to fit, This PR is recomended paired with #402 and others updated looks PRs

This bring new floors sprites from baystation, paradise station.

---

# TODO

- [x] Import Sprites
- [x] @VMSolidus Edits

---

<details><summary><h1>Media</h1></summary>
<p>

image
image
image
image
image

</p>
</details>

---

# Changelog

:cl:
- tweak: Floors Looks Updated/Resprited.

### CODE REVIEW

**Comment by LovelyLophi** [comment]
I'm not a fan of this change, the floors being flat and kinda dull in relation to characters is good for a background.

There are a lot of sprites that could be improved but the floors really don't need it.

**Comment by stellar-novas** [comment]
I think the changes look good, but I want to see them in game

**Review by VMSolidus — APPROVED** [review]
image

VERY nice when paired with our other sprite updates.

**Comment by DangerRevolution** [comment]
I'd like to see lots of tiles together on the Dev map, just to see the range.
Does this resprite every tile?

**Comment by VMSolidus** [comment]
> I'd like to see lots of tiles together on the Dev map, just to see the range. Does this resprite every tile?

image

It doesn't resprite every tile, just the essential ones that are in common usage. All the key floortiles and floor decals. The main point of the change is correcting lighting for the base tiles, so this doesn't actually affect the weathering decals(which are automatically placed on map init). It isn't touching specialized ones like wood tiles.

**Comment by FoxxoTrystan** [comment]
> > I'd like to see lots of tiles together on the Dev map, just to see the range. Does this resprite every tile?
> 
> image
> 
> It doesn't resprite every tile, just the essential ones that are in common usage. All the key floortiles and floor decals. The main point of the change is correcting lighting for the base tiles, so this doesn't actually affect the weathering decals(which are automatically placed on map init). It isn't touching specialized ones like wood tiles.

AAAAA
image
Offset!

**Comment by VMSolidus** [comment]
> > > I'd like to see lots of tiles together on the Dev map, just to see the range. Does this resprite every tile?
> > 
> > 
> > image
> > It doesn't resprite every tile, just the essential ones that are in common usage. All the key floortiles and floor decals. The main point of the change is correcting lighting for the base tiles, so this doesn't actually affect the weathering decals(which are automatically placed on map init). It isn't touching specialized ones like wood tiles.
> 
> AAAAA image Offset!

Just now fixed it. :)

**Review by DangerRevolution — APPROVED** [review]
Can't get the PR to build so going to assume off of visuals that this is safe.

**Pull request merged**
