### PR TITLE
Alcohol Ethanol Content Fix

### PR DESCRIPTION
**Pull request by SleepyScarecrow**
# Description

I changed the ethanol content of all of the drinks and base alcohols within the game based off of irl parallels and math for the sake of realism and because it bugged the shit out of me that it was so inconsistent.

---

# Changelog

:cl:
- tweak: Ethanol Contents
- fix: SnowWhite Recipe
- tweak: Ethanol overdose changed from 15 to 45

### CODE REVIEW

**Review by VMSolidus — CHANGES_REQUESTED** [review]
Can you do me a favor and literally double or triple the overdose threshold for Ethanol? Maybe quadruple it? Because we're already at a point where if people polish off an entire drink, there's a significant chance that they're just going to fucking die. 
"Whoops I drank a gargle blaster. Time to suddenly collapse dead in the bar"

**Comment by SleepyScarecrow** [comment]
holy shit it was at 15???
yeah done, I'll make it 45

**Comment by SleepyScarecrow** [comment]
wait shit don't merge this yet i forgot to do the DV drinks

**Comment by SleepyScarecrow** [comment]
okay we're good

**Review by VMSolidus — APPROVED** [review]

**Review by OldDanceJacket — APPROVED** [review]

**Pull request merged**
