### PR TITLE
Revert PR #56 through #76

### PR DESCRIPTION
**Pull request by VMSolidus**
# Description

There was a miscommunication, and I bungled the repository during the last round of merges. The Mirror Bot is not quite finished yet, and some polishing needs to happen behind the scenes before we can actually start doing this. Also new policies from the discord are pending regarding how these PRs need to be handled. I'll need to either reopen or remake the reverted PRs, since we do actually still need them. But we need PRs mirrored from Wizards' Den in order to go through the list properly. 

image

### CODE REVIEW

**Comment by DEATHB4DEFEAT** [comment]
I think the bot might be offended by this.

image

**Comment by DEATHB4DEFEAT** [comment]
> I'll need to either reopen or remake the reverted PRs

You can revert this revert PR

**Review by DEATHB4DEFEAT — APPROVED** [review]

**Review by SimpleStation14 — APPROVED** [review]

**Comment by DEATHB4DEFEAT** [comment]
Oh he's fine with it

**Comment by SimpleStation14** [comment]
:robot::+1:

**Pull request merged**
