### PR TITLE
Feat: Loadout Profiles (Draft)

### PR DESCRIPTION
**Pull request by Mnemotechnician**
# Description
This is a draft for an implementation of a solution for loadout profile loading/saving and per-job loadout preferences proposed as in a result of the discussion in #1136.

This PR adds loadout profiles. Each player can have an unlimited number of profiles associated with them. Each profile has a name and a list of items included in it. The player can create per-job loadout preferences, which would make the game automatically load a specific profile instead of their currently chosen one.

This also refactors some parts of the loadouts code that I got particularly mad about.

# TODO
- [ ] Backend support (partial)
  - [X] Basic DB/OOP model support
  - [X] DB/OOP character profile conversions
  - [ ] Automatic loadout profile loading based on the players job
  - [ ] Per-character default loadout profiles
  - [ ] Better DB migrations (migrate existing loadouts to the new system, if possible)
- [ ] Frontend support:
  - [X] Make the client not crash
  - [ ] Hide the loadouts tab container when no profile is chosen, and propose the player to create a new profile or select one instead
  - [ ] Display the current profile in the character editor
  - [ ] Support for creating, renaming, and removing profiles
  - [ ] Loadout job preferences dialog (or maybe that could be implemented as selectors in the jobs tab instead - we'll see)
- [ ] Testing
- [ ] Something else I guess

<details><summary><h1>Media</h1></summary>
<p>

TODO

image

</p>
</details>

# Changelog
TODO cl

### CODE REVIEW

**Comment by VMSolidus** [comment]
We have already collectively decided among all of the Einstein Engines maintainers that we wish to go with the solution proposed by Danger Revolution at https://github.com/Simple-Station/Einstein-Engines/issues/1136#issuecomment-2433515170 , and will not be going with the solution you have proposed. Since nobody is currently working on Danger Revolution's proposal, you are more than welcome to work on it if you wish.

**Comment by Mnemotechnician** [comment]
> We have already collectively decided among all of the Einstein Engines maintainers that we wish to go with the solution proposed by Danger Revolution at [#1136 (comment)](https://github.com/Simple-Station/Einstein-Engines/issues/1136#issuecomment-2433515170) , and will not be going with the solution you have proposed. Since nobody is currently working on Danger Revolution's proposal, you are more than welcome to work on it if you wish.

Please read the PR description or code for once. This IS the danger's solution.

**Comment by VMSolidus** [comment]
> > We have already collectively decided among all of the Einstein Engines maintainers that we wish to go with the solution proposed by Danger Revolution at [#1136 (comment)](https://github.com/Simple-Station/Einstein-Engines/issues/1136#issuecomment-2433515170) , and will not be going with the solution you have proposed. Since nobody is currently working on Danger Revolution's proposal, you are more than welcome to work on it if you wish.
> 
> Please read the PR description or code for once. This IS the danger's solution.

It was not clear that you were making Danger's solution, because you mentioned limited profile numbers in the PR description, I apologize for the misunderstanding. This is fine.

**Comment by Mnemotechnician** [comment]
Although- it would seem I miscalculated a bit, and danger proposed slightly more than I was aiming for with this PR - I was intending to create something like subprofiles, rather than complete separate character profiles. I can close it and maybe begin anew later, if I- get some motivation to do so.

**Pull request closed without merging**
