### PR TITLE
Adjust Air Alarm Pressure Thresholds

### PR DESCRIPTION
**Pull request by zelezniciar1**
# Description

- Adjusts the "danger" status threshold in Air Alarms to 20 kPa, resulting in "warning" status at the expected 90 kPa. 
- Fixes the issue where air alarms had "danger" status at 20 kPa and "warning" status at 21 kPa

---

# Changelog

:cl: zelezniciar
- fix: Fixes Air Alarms not entering danger/warning state when pressure is low

### CODE REVIEW

**Comment by Mnemotechnician** [comment]
This is intentional, you do NOT want firelocks to bolt at 85 kpa.

**Comment by zelezniciar1** [comment]
It could be set lower, but doesn't being under 85 kPa mean that internals are needed, therefore, it's no longer safe?

**Comment by Mnemotechnician** [comment]
that's what warning is for

**Comment by FoxxoTrystan** [comment]
A thing i wana note is again the airalarm go in warning state IF the air is not NORMAL.

That is a warning.

**Comment by zelezniciar1** [comment]
Alright, I've altered it so 0-20 kPa is "danger" status, and 20-90 is "warning"

**Review by VMSolidus — APPROVED** [review]

**Review by DEATHB4DEFEAT — APPROVED** [review]

**Pull request merged**
