### PR TITLE
Port Justice Department From DeltaV

### PR DESCRIPTION
**Pull request by VMSolidus**
# Description

This ports https://github.com/DeltaV-Station/Delta-v/pull/660

> ## About the PR
> Adds the Justice Department, a department enveloping the lawyer and 3 new roles that manage the court system and charges against the accused. Includes: • New department, Justice! • 3 new roles: ◦ Chief Justice: The main, impartial judge for the station responsible for adjudicating criminal and civil trials, as well as other small matters like paroles and pardons. ◦ Clerk: The court clerk, who organizes trials, notarizes court documents (warrants, sentences, etc), and ensures correct sentencing and due process for the accused in sec custody. ◦ Prosecutor: A special lawyer role that legally advises sec and handles all of its court prep and prosecution, freeing up sec's time to go stun baton the clown instead of waiting for trial. • Antag objective to steal the Clerk's notary stamp, an object imbued with the authority to officialize court decisions. • Made the Lawyer role easier to understand and added them to the department. Renamed to Attorney, they now exclusively defend the accused or can sue on their behalf. Can also curse at the prosecutor in the bar. • Changed SoP to match. Notable changes include ◦ Felony charges and above must be reviewed and approved by the Clerk or Chief Justice if those roles are active. ◦ Parole, criminal trials, and civil trials are now all adjudicated by the Chief Justice, or the clerk in their absence. ◦ To ensure fair judgement, a Captain can only remove the Chief Justice with a majority vote from command. ◦ Warrants and court decisions must be written down and stamped with the notary stamp. Warrants must be approved by the Chief Justice. ◦ Full list of SoP changes can be found here: https://docs.google.com/document/d/12ZKTtzvVWBuC7PuiREL9v7mhVZve11p0-T6MBPpVeGs/edit?usp=sharing • Classy wooden desk timer to help keep trials timely and within limits.
> 
> **TO DO:** Chief Justice
> 
> * [x]  Role
> * [x]  Inventory
> * [x]  Job Description
> * [x]  Icon
> * [x]  Access (CMD/CJ/Sec/Justice*)
> * [x]  Airlocks
> * [x]  Spawnpoint
> * [x]  Closet(just reuse legal w/ a lock)
> * [x]  Gavel** (proto/sprite/sound)
> * [x]  Stamp (proto/sprite)
> * [x]  Drip
> 
> Court Clerk
> 
> * [x]  Role
> * [x]  Inventory
> * [x]  Job Description
> * [x]  Icon
> * [x]  Access (Sec/Justice*)
> * [x]  Spawnpoint
> * [x]  Closet(just reuse legal w/ a lock)
> * [x]  Stamp** (proto/sprite)
> * [x]  Warrant document
> * [x]  Drip
> 
> Prosecutor
> 
> * [x]  Role
> * [x]  Inventory
> * [x]  Job Description
> * [x]  Icon
> * [x]  Access (Sec/Justice*)
> * [x]  Spawnpoint
> * [x]  Closet(just reuse legal w/ a lock)
> * [x]  Drip(Can be same as lawyer but should have a unique badge)
> 
> SoP/Guidlines
> 
> * [x]  Civil and criminal law-penalties
> * [x]  Legal mutiny?
> * [x]  Assigning judges when no judge is present
> * [x]  Judge is representative of CC. Not necessarily _above_ captain but outside.
> * [x]  When to appeal to a jury? How to pick a jury? (random would be good)
> * [x]  Rules for gaining warrants
> * [x]  Procedure for arresting officer filing criminal charges
> * [x]  Rules for summoning witnesses
> * [ ]  Guide/book
> 
> Other
> 
> * [ ]  Station Beacons
> 
> ## Notes:
> * We might want to consider bringing back brig access for cells to give legal dept sec access and not control over prisoners.
> * Mapping would need to provide offices for CJ, CC, and Prosecuter.
> * Chief Justice is a rep of CC not necessarily above captain but outside
> 
> ## Why / Balance
> The current legal system in-game is built around LRP gameplay, with security handling everything relating to arrests, sentencing, trials, and execution. Additionally, it is near-impossible to find an impartial judge for any court case with the current system. New legal department would guarantee an impartial and available judge (whether it be the Chief Justice or Clerk) for any court case, take pressure off of security to handle things like sentencing and trials. Additionally, there will be more roleplay opportunities for things like civil cases, inter-department disputes, internal affairs, or whatever else you may need legal help with.
> 
> ## Technical details
> n/a
> 
> ## Media
> image image
> 
> * [x]  I have added screenshots/videos to this PR showcasing its changes in-game, **or** this PR does not require an in-game showcase
> 
> ## Breaking changes
> none that I know of 😓
> 
**Changelog** 🆑 Leo, Velcroboy, and Timemaster 
- add: Added The Justice Department >:)

### CODE REVIEW

**Comment by Mnemotechnician** [comment]
No, no no no.
Delta playerbase already hates it, we definitely don't need it here.

**Comment by DangerRevolution** [comment]
> No, no no no. Delta playerbase already hates it, we definitely don't need it here.

this is needed for all future updates

**Comment by leonardo-dabepis** [comment]
> No, no no no. Delta playerbase already hates it, we definitely don't need it here.

Delta playerbase hates everything good + they don't understand roleplay (essential for a roleplay-based department) + most of them refuse to read space law and SOP or even the game rules + the department was unfinished at time of release which caused sec mains to have a permanent hateboner for it + the things that made it bad were fixed a month ago + it loses so much potential from being only on Delta because it is NOT taken seriously over there _at all_ + L + ratio

But I like to think that it'd work better for a roleplay-based codebase such as EE.

**Comment by ShatteredSwords** [comment]
Security needs an opposing force to prevent what people call "ShitSec". Space law is supposed to do that, but it doesn't work in a multitude of servers. Having an entire department that revolves around keeping security in check WITH space law, while being good for roleplay, is honestly THE solution, unless those of you who oppose have a better one that doesn't include admin intervention. I think this is a great department to have, in the right hands.

**Comment by TadJohnson00** [comment]
> No, no no no. Delta playerbase already hates it, we definitely don't need it here.

The more the Delta playerbase hates something, the more it's worth porting as a general rule. To succinctly sum up what Leo said - at the risk of appearing facetious - Delta V, broadly generalised, is more concerned as a whole about mechanical advantages, meming and shitter behaviour, and exerting their own generally infantile will on the station and community as a whole.

Justice, originally intended to be a more serious department, would work for a more conscientious playerbase, stronger admin intervention, and generally better players, to fulfill its role of facilitating security efforts and general station upkeep. If you don't want it to turn out like Delta, put better players in Security and Justice - and, well, pretty much every department. Plus, as mentioned, it's an integral part of Delta V's maps and general SOP, even if you disagree with Security having any checks or balances; it's gotta happen unless you're reworking it more or less from the ground up.

**Comment by DangerRevolution** [comment]
Once we get Delta-V maps ported; there'll be variants made without the Justice department (primarily as we don't have SoP or SL guidebooked). This is needed for future departments.

About above ^
Delta-V struggles with chronic shitterism. Until all the people saying "I refuse to do Paperwork RP" or "I am not going to read SoP, CP or SL" are permabanned from Delta, Justice will never work as intended. It'll be made to work on EE one day, that isn't today. This is just a stepping stone PR.

**Comment by DangerRevolution** [comment]
Also, this is being set to draft until the TODO is done.

**Comment by VMSolidus** [comment]
> Also, this is being set to draft until the TODO is done.

Not my TODO, not going to fucking do that. Fuck no. This is a cherry-pick of a content PR required so that we can continue doing our work of cherry-picking Delta. This PR changes literally nothing about how our codebase plays. Our maps still have Lawyer, none of the new jobs even spawn in maps. I'm re-opening this PR.

**Review by DangerRevolution — APPROVED** [review]

**Review by OldDanceJacket — APPROVED** [review]

**Comment by OldDanceJacket** [comment]
> > No, no no no. Delta playerbase already hates it, we definitely don't need it here.
> 
> Delta playerbase hates everything good + they don't understand roleplay (essential for a roleplay-based department) + most of them refuse to read space law and SOP or even the game rules + the department was unfinished at time of release which caused sec mains to have a permanent hateboner for it + the things that made it bad were fixed a month ago + it loses so much potential from being only on Delta because it is NOT taken seriously over there _at all_ + L + ratio
> 
> But I like to think that it'd work better for a roleplay-based codebase such as EE.

It's a horribly implemented department in every aspect that fails at the whiteboard suggestion stage. 

It takes an aspect of the game(courtroom rp) that isn't meant to be an every round thing, that suffers from players meandering through the roleplay of it because and has to have a number of things line up perfectly to happen and usually is just ten minutes of people taking forever to type. Courtroom RP should've had attention given to it, some rules refined for Lawyers and those that wished to engage in it, but the solution was to make the process as quick and painless as possible.

Not to butcher SOP, space law, every map, and the flow of the round by trying to make it not only happen every round(still doesn't happen lmao) and to make it so it takes even LONGER to get through it.

It doesn't aid rp, it doesn't introduce more interesting scenarios, and it bogs down the majority of the game elsewhere. There are zero positives related to the **Justice Department**.

Anyways I'm merging.

**Pull request merged**
